/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fppplayer;

/**
 *
 * @author David
 */
public class jfFPPplayer extends javax.swing.JFrame {

  /**
   * Creates new form jfFPPplayer
   */
  public jfFPPplayer() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLayeredPane1 = new javax.swing.JLayeredPane();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jLayeredPane2 = new javax.swing.JLayeredPane();
    jLabel2 = new javax.swing.JLabel();
    jButton4 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));
    setResizable(false);

    jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Current Playlist Details:"));
    jLayeredPane1.setOpaque(true);

    jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton2.setText("Start");
    jButton2.setBounds(150, 250, 59, 23);
    jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

    jButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton3.setText("Stop Gracefully");
    jButton3.setMaximumSize(new java.awt.Dimension(59, 23));
    jButton3.setMinimumSize(new java.awt.Dimension(59, 23));
    jButton3.setPreferredSize(new java.awt.Dimension(59, 23));
    jButton3.setBounds(210, 250, 110, 23);
    jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

    jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton1.setText("Stop");
    jButton1.setMaximumSize(new java.awt.Dimension(59, 23));
    jButton1.setMinimumSize(new java.awt.Dimension(59, 23));
    jButton1.setPreferredSize(new java.awt.Dimension(59, 23));
    jButton1.setBounds(330, 250, 59, 23);
    jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null},
        {null, null, null},
        {null, null, null},
        {null, null, null}
      },
      new String [] {
        "#", "Song Name", "Sequence Name"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, true
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jTable1.setColumnSelectionAllowed(true);
    jTable1.setGridColor(new java.awt.Color(255, 255, 255));
    jTable1.setInheritsPopupMenu(true);
    jScrollPane1.setViewportView(jTable1);
    jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jTable1.getColumnModel().getColumn(0).setMinWidth(20);
    jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
    jTable1.getColumnModel().getColumn(0).setMaxWidth(20);
    jTable1.getColumnModel().getColumn(1).setMinWidth(40);
    jTable1.getColumnModel().getColumn(1).setPreferredWidth(40);
    jTable1.getColumnModel().getColumn(1).setMaxWidth(40);
    jTable1.getColumnModel().getColumn(2).setMinWidth(40);
    jTable1.getColumnModel().getColumn(2).setPreferredWidth(40);
    jTable1.getColumnModel().getColumn(2).setMaxWidth(40);

    jScrollPane1.setBounds(20, 30, 499, 210);
    jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

    jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FPPD Daemon Status:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));
    jLayeredPane2.setOpaque(true);

    jLabel2.setText("FPPD daemon is running");
    jLabel2.setBounds(30, 24, 330, 20);
    jLayeredPane2.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLabel2.getAccessibleContext().setAccessibleName("lblFPPDstatus");

    jButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton4.setText("Start FPPD");
    jButton4.setBounds(440, 20, 83, 23);
    jLayeredPane2.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(0, 0, Short.MAX_VALUE)
            .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 541, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(jLayeredPane2))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(jLayeredPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
        .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 283, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(143, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(jfFPPplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(jfFPPplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(jfFPPplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(jfFPPplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new jfFPPplayer().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLayeredPane jLayeredPane1;
  private javax.swing.JLayeredPane jLayeredPane2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  // End of variables declaration//GEN-END:variables
}
