#!/bin/bash

. /opt/fpp/scripts/common
. /opt/fpp/scripts/functions

RTCDEVICE="/dev/rtc0"

if [ "${FPPPLATFORM}" = "BeagleBone Black" ]
then
	RTCDEVICE="/dev/rtc1"
fi

if [ -e ${RTCDEVICE} ]; then
    hwclock -s -f ${RTCDEVICE}  > /dev/null 2>&1
fi

