services:
  fpp:
    build:
      args:
        EXTRA_INSTALL_FLAG: --skip-clone --skip-apt-install --yes
        FPPBRANCH: ${FPPBRANCH}
      context: ../
      dockerfile: ./Docker/Dockerfile
    hostname: fpp-docker
    volumes:
      - ../:/opt/fpp
    restart: always
    ports:
      - "8080:80/tcp"
    cap_add:
      - SYS_PTRACE
      - SYS_NICE
