<?
header("Access-Control-Allow-Origin: *");

$skipJSsettings = 1;
require_once "common.php";

DisableOutputBuffering();

# Any file not starting with a / is assumed to be under $mediaDirectory
# which is normally /home/fpp/media
$files = array();
$files['scripts'] = array(
    'scripts/*',
);
$files['caches'] = array(
    'cache/*',
    'config/media_durations.cache',
    'tmp/*',
);
$files['backups'] = array(
    'backups/*',
    'config/backups',
);
$files['config'] = array(
    'config/.htaccess',
    'config/.htpasswd',
    'config/authorized_keys',
    'config/dns',
    'config/gpio.json',
    'config/instantCommand.json',
    'config/model-overlays.json',
    'config/virtualdisplaymap',
    'fpp-info.json',
    'exim4/*',
    'config/cape-eeprom.bin',
);
$files['network'] = array(
    'config/interface.*',
    '/var/lib/connman/fpp.config',
);
$files['media'] = array(
    'images/*',
    'music/*',
    'videos/*',
);
$files['sequences'] = array(
    'sequences/*',
);
$files['effects'] = array(
    'effects/*',
);
$files['playlists'] = array(
    'playlists/*',
);
$files['channeloutputs'] = array(
    'config/co-bbbStrings.json',
    'config/channeloutputs.json',
    'config/co-other.json',
    'config/co-pixelStrings.json',
    'config/co-universes.json',
    'config/co-pwm.json',
);
$files['eeprom'] = array(
    'config/cape-eeprom.bin',
    'config/co-pixelStrings.json',
    'config/co-bbbStrings.json',
    'tmp/cape-info.json',
);
$files['schedule'] = array(
    'config/schedule.json',
);
$files['settings'] = array(
    'settings',
);
$files['uploads'] = array(
    'upload/*',
);
$files['logs'] = array(
    'logs/*',
);
$files['plugins'] = array(
    'plugins/*',
);
$files['pluginConfigs'] = array(
    'config/plugin.*',
    'plugindata/*',
);
$files['user'] = array(
    '/home/fpp/.bash_history',
    '/home/fpp/.ssh/authorized_keys',
    '/home/fpp/.ssh/known_hosts',
    '/root/.bash_history',
    '/root/.ssh/authorized_keys',
    '/root/.ssh/known_hosts',
);
# Media-dir PipeWire config files (user-configured routing, groups, AES67, Opus RTP).
# The dynamically-generated OS conf files under /etc/pipewire/pipewire.conf.d/
# (95/96/97 — regenerated by FPPINIT at boot) are also removed here so the OS
# state matches the cleared media config.  The static FPP overlay files
# (90-fpp.conf, 10-fpp-alsa.conf, 15-fpp-usb-audio-headroom.conf, and the
# WirePlumber 60-fpp-block-combine-fallback hook) are NOT touched — they are
# shipped with the image, hardware-independent, and required for PipeWire to
# start / route correctly.
# After file removal this area also resets MediaBackend to pipewire-simple and clears
# all PipeWire-specific settings, then restarts the PipeWire services.
$files['audiobackend'] = array(
    'config/pipewire-audio-groups.json',
    'config/pipewire-audio-groups.conf',
    'config/pipewire-audio-groups-simple.json',
    'config/pipewire-input-groups.json',
    'config/pipewire-input-groups.conf',
    'config/pipewire-aes67-instances.json',
    'config/pipewire-opus-rtp-instances.json',
    'config/pipewire-video-groups.json',
    'config/pipewire-video-groups-simple.json',
    'config/pipewire-video-consumers.json',
    'config/pipewire-video-input-sources.json',
    'config/pipewire-video-input-sources-gen.json',
    '/etc/pipewire/pipewire.conf.d/95-fpp-alsa-sink.conf',
    '/etc/pipewire/pipewire.conf.d/96-fpp-input-groups.conf',
    '/etc/pipewire/pipewire.conf.d/97-fpp-audio-groups.conf',
);

?>
Resetting FPP Configuration
======================================================================
Removing files:
<?
$areas = array();
if (isset($_GET['areas'])) {
    $areasStr = $_GET['areas'];
    $areasStr = preg_replace('/,dummy/', '', $areasStr);
    $areas = preg_split('/,/', $areasStr);
}

foreach ($areas as $area) {
    printf("Area: %s\n", $area);
    foreach ($files[$area] as $file) {
        $base = $settings['mediaDirectory'] . '/';
        if (substr($file, 0, 1) == '/') {
            $base = '';
        }
        if (preg_match('/[?\*]/', $file)) {
            $filesInDir = glob($base . $file); // get all file names
            foreach ($filesInDir as $fileToRemove) { // iterate files
                if (is_file($fileToRemove)) {
                    printf("%s\n", $fileToRemove);
                    unlink($fileToRemove); // delete file
                } else if (is_dir($fileToRemove)) {
                    $di = new RecursiveDirectoryIterator($fileToRemove, FilesystemIterator::SKIP_DOTS);
                    $ri = new RecursiveIteratorIterator($di, RecursiveIteratorIterator::CHILD_FIRST);
                    foreach ($ri as $fileToRemove2) {
                        printf("%s\n", $fileToRemove2);
                        $fileToRemove2->isDir() ? rmdir($fileToRemove2) : unlink($fileToRemove2);
                    }
                    rmdir($fileToRemove);
                }
            }
        } else if (file_exists($base . $file)) {
            printf("%s%s\n", $base, $file);
            unlink($base . $file); // delete file
        }
    }
    printf("\n");
}

flush();

if (in_array('audiobackend', $areas)) {
    printf("\nResetting audio backend settings...\n");

    # Reset MediaBackend to the safe minimal PipeWire mode
    WriteSettingToFile('MediaBackend', 'pipewire-simple');
    printf("  MediaBackend reset to pipewire-simple\n");

    # Clear PipeWire output routing settings
    $pipewireSettings = array(
        'PipeWireSinkName', 'PipeWireSinkName_2', 'PipeWireSinkName_3',
        'PipeWireSinkName_4', 'PipeWireSinkName_5',
        'PipeWireVideoSinkName', 'PipeWireVideoSinkName_2', 'PipeWireVideoSinkName_3',
        'PipeWireVideoSinkName_4', 'PipeWireVideoSinkName_5',
        'PipeWirePrimaryOutput', 'ForceAudioId',
        'AES67Enabled',
    );
    foreach ($pipewireSettings as $setting) {
        DeleteSettingFromFile($setting);
        printf("  Cleared setting: %s\n", $setting);
    }

    printf("\nRestarting PipeWire services...\n");
    exec($SUDO . ' systemctl restart fpp-pipewire.service fpp-wireplumber.service fpp-pipewire-pulse.service 2>&1', $output, $ret);
    foreach ($output as $line) {
        printf("  %s\n", $line);
    }
    if ($ret === 0) {
        printf("  PipeWire services restarted successfully.\n");
    } else {
        printf("  WARNING: PipeWire services restart returned exit code %d.\n", $ret);
    }
    flush();
}
?>