#!/bin/bash
### BEGIN INIT INFO
# Provides:          fppinit
# Required-Start:    $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     S
# Default-Stop:
# Short-Description: FPP OS image initialization
# Description:       FPP OS image initialization
### END INIT INFO
#########################################################################
# /etc/init.d/fppinit: setup OS image for FPP
#########################################################################


export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
BINDIR="/opt/fpp/scripts"

FPPHOME="/home/pi"

if [ -d "/home/fpp" ]
then
        FPPHOME="/home/fpp"
fi

if [ -x "${FPPHOME}/fpp/scripts/fpp_init" ]
then
	BINDIR="${FPPHOME}/fpp/scripts"
fi

${BINDIR}/fpp_init $1

exit 0
