#!/bin/bash
### BEGIN INIT INFO
# Provides:          fppstart
# Required-Start:    $all
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Start FPP
# Description:       Start FPP
### END INIT INFO
#########################################################################
# /etc/init.d/fppstart: Start FPP
#########################################################################


export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
BINDIR="/opt/fpp/scripts"

FPPHOME="/home/pi"

if [ -d "/home/fpp" ]
then
        FPPHOME="/home/fpp"
fi

if [ -x "${FPPHOME}/fpp/scripts/fpp_start" ]
then
	BINDIR="${FPPHOME}/fpp/scripts"
fi

${BINDIR}/fpp_start $1

exit 0
