#!/bin/sh
#############################################################################

BINDIR=$(dirname $0)
. ${BINDIR}/common

logOutput

if [ -f "${CFGDIR}/dns" ]
then
	. ${CFGDIR}/dns

	if [ "x${DNS1}" != "x" -o "x${DNS2}" != "x" ]
	then
		cp -f /etc/resolv.conf /etc/resolv.conf.orig
		cat /etc/resolv.conf.orig | grep -v nameserver > /etc/resolv.conf

		if [ "x${DNS1}" != "x" ]
		then
			echo "Configuring ${DNS1} as nameserver"
			echo "nameserver ${DNS1}" >> /etc/resolv.conf
		fi

		if [ "x${DNS2}" != "x" ]
		then
			echo "Configuring ${DNS2} as nameserver"
			echo "nameserver ${DNS2}" >> /etc/resolv.conf
		fi
	fi
fi

