#!/bin/bash
#############################################################################
# Main guts

BINDIR=$(dirname $0)
. ${BINDIR}/common
. ${BINDIR}/functions

logOutput

SetupFPPNetworkConfig

