#! /usr/bin/php
<?php


$dir = '/home/fpp/media/tmp/';
$it = new RecursiveDirectoryIterator($dir, RecursiveDirectoryIterator::SKIP_DOTS);
$files = new RecursiveIteratorIterator($it,
             RecursiveIteratorIterator::CHILD_FIRST);
foreach($files as $file) {
    if ($file->isDir()){
        rmdir($file->getRealPath());
    } else {
        unlink($file->getRealPath());
    }
}

if (!file_exists("/home/fpp/media/tmp") && !is_dir("/home/fpp/media/tmp")) {
     mkdir("/home/fpp/media/tmp");
}

// detect and initialize the eeprom, only support 24c256 chips for now
if (!file_exists("/sys/bus/i2c/devices/2-0050/eeprom")) {
    file_put_contents("/sys/bus/i2c/devices/i2c-2/new_device", "24c256 0x50");
}

if (!file_exists("/sys/bus/i2c/devices/2-0050/eeprom")) {
    exit(0);    
}
$fp = fopen('/sys/bus/i2c/devices/2-0050/eeprom', 'rb');
$header = fread($fp, 6); // should be FPP02 + null
$cape = fread($fp, 26); // cape name + nulls
$capev = fread($fp, 10); // cape version + nulls
$capev = fread($fp, 16); // cape serial# + nulls

$flen = fread($fp, 6); //length of the file
$flen = intval($flen);
while ($flen != 0) {
    $flags = fread($fp, 2);
    $fname = fread($fp, 64);
    $fname = trim($fname);
    $fdata = fread($fp, $flen);
    $path = '/home/fpp/media/' . $fname;
    $fout = fopen($path, "wb");
    fwrite($fout, $fdata);
    fclose($fout);

    if ($flags == 1) {
        $dirname = dirname("/home/fpp/media/" . $fname);
        exec("cd $dirname ; unzip /home/fpp/media/$fname 2>&1", $output, $result);
        var_dump($output);
    }

    $flen = fread($fp, 6); //length of the file
    $flen = intval($flen);
}

fclose($fp);


if (file_exists("/home/fpp/media/tmp/cape-info.json")) {
    $json = json_decode(file_get_contents("/home/fpp/media/tmp/cape-info.json"));
    foreach ($json->defaultSettings as $key => $value) {
        if (strpos(file_get_contents("/home/fpp/media/settings"), $key . " =") == false) {
            file_put_contents("/home/fpp/media/settings", $key . " = \"" . $value . "\"\n", FILE_APPEND);
        }
    }
}

file_put_contents("/sys/bus/i2c/devices/i2c-2/delete_device", "0x50");

?>
