#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common
. ${BINDIR}/functions

if [ ! -d ${LOGDIR} ]
then
	mkdir -p ${LOGDIR}
	chown ${FPPUSER}.${FPPUSER} ${LOGDIR}
	chmod 775 ${LOGDIR}
fi

if [ ! -f "${MEDIADIR}/.auto_update_disabled" ]
then
	${SCRIPTDIR}/git_pull
fi

remountRootReadWrite

${SCRIPTDIR}/upgrade_config

${SCRIPTDIR}/timezone_sync

remountRootReadOnlyIfNeeded

if [ -f "/usr/bin/config-pin" ]
then
   /usr/bin/config-pin -f ${BINDIR}/bbb-pins.txt
fi


${SUDO} ${SCRIPTDIR}/fppd_start

