#!/bin/bash
##############################################################################
# This script is run via /etc/init.d/fppinit at system boot to allow us to
# initialize certain things before the system starts booting.
##############################################################################
# NOTE: The ONLY supported action currently is 'start', so if we're called
#       with anything else, we exit
if [ "x$1" != "xstart" ]
then
	echo "$0 called with unsupported action of '$1'."
	exit 0
fi
#
##############################################################################
# Some internal setup
PATH="/sbin:/bin:/usr/sbin:/usr/bin"

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common
. ${BINDIR}/functions

##############################################################################
# Perform enough line feeds to put the rest of our output at the bottom of the
# screen so the splash video can show at the top
# Disable for now until we get the omxplayer dbus issue worked out
#perl -e "printf( \"\n\" x 50 );"

##############################################################################
# Start the splash video in the background
# Disable for now until we get the omxplayer dbus issue worked out
#${FPPDIR}/etc/asplashscreen &

##############################################################################
echo "FPP - Performing initial pre-start setup"
##############################################################################
echo "    - Setting default network config"
if [ "${FPPPLATFORM}" = "BeagleBone Black" ]
then
    echo "Skipping default network config, was done at setup time"
else
    SetupDefaultNetworkConfig
fi

##############################################################################
echo "    - Checking SSH keys"
SSHKEYS=$(ls -al /etc/ssh/ssh_host*key* 2> /dev/null | wc -l)
if [ ${SSHKEYS} -eq 0 ]
then
	echo "      - Renerating SSH keys"
	ssh-keygen -A
fi

##############################################################################

echo "FPP - Running ${BINDIR}/startup"
${BINDIR}/startup
