#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common
. ${BINDIR}/functions

if [ ! -d ${LOGDIR} ]
then
	mkdir -p ${LOGDIR}
	chown ${FPPUSER}.${FPPUSER} ${LOGDIR}
	chmod 775 ${LOGDIR}
fi

if [ ! -f "${MEDIADIR}/.auto_update_disabled" ]
then
    WaitForInterfacesUp
	${SCRIPTDIR}/git_pull
fi

remountRootReadWrite

${SCRIPTDIR}/upgrade_config

${SCRIPTDIR}/timezone_sync

remountRootReadOnlyIfNeeded

if [ "${FPPPLATFORM}" = "BeagleBone Black" ]
then
	configureGPIOPins
fi

${SUDO} ${SCRIPTDIR}/fppd_start

