#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common
. ${BINDIR}/functions


echo "Stopping fppd"
${SUDO} ${FPPDIR}/scripts/fppd_stop

cd ${FPPDIR}/src/

echo "Cleaning FPPD"
#cleanCompiledBinaries
sudo -u ${FPPUSER} make clean

echo "Compiling FPPD"
#compileBinaries
sudo -u ${FPPUSER} make optimized

echo "Restarting fppd"
${SUDO} ${FPPDIR}/scripts/fppd_start

