#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common
. ${BINDIR}/functions

logOutput

stopWebSocketServer

runPreStopScripts

echo "Stopping fppd"
# Stop any running playlist
${FPPBINDIR}/fpp -q > /dev/null 2>&1
sleep 1
# make sure fppd is dead
killall -9 fppd

runPostStopScripts

stopOLADaemonIfUnused

