#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common
. ${BINDIR}/functions


if [ ! -x ${FPPBINDIR}/fppd ]; then
   echo "${FPPBINDIR}/fppd doesn't exist, try building it"
   cleanCompiledBinaries
   compileBinaries
fi

##############################################################################
# Leave these things till last so user can see output of anything above here
##############################################################################
applyScreenBlankSetting

. ${SCRIPTDIR}/fppd_start
