#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

# See if we should be running from /home/fpp/fpp
if [ "x${BINDIR}" == "x/opt/fpp/scripts" -a -f "/home/fpp/fpp/scripts/fppd_boot" ]
then
    exec /home/fpp/fpp/scripts/fppd_boot
fi

. ${BINDIR}/common
. ${BINDIR}/functions


if [ ! -x ${FPPBINDIR}/fppd ]; then
   echo "${FPPBINDIR}/fppd doesn't exist, try building it"
   cleanCompiledBinaries
   compileBinaries
fi

##############################################################################
# Leave these things till last so user can see output of anything above here
##############################################################################
applyScreenBlankSetting

. ${SCRIPTDIR}/fppd_start
