#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common
. ${BINDIR}/functions

cd ${FPPDIR}

logOutput

# Clear any restart flag
sed -i -e "s/^restartFlag .*/restartFlag = 0/" ${FPPHOME}/media/settings

echo "Setup channel outputs"
setupChannelOutputs

echo "Running pre-start scripts"
runPreStartScripts

if [ ! -x ${FPPBINDIR}/fppd ]; then
   echo "${FPPBINDIR}/fppd doesn't exist, try building it"
   cleanCompiledBinaries
   compileBinaries
fi

echo "Starting ${FPPBINDIR}/fppd"
nice -n -20 ${FPPBINDIR}/fppd --config-file ${FPPHOME}/media/settings --daemonize

# FIXME, find a better way to wait until fppd is up before continuing
sleep 2

runPostStartScripts

