#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common
. ${BINDIR}/functions

if [ ! -x ${FPPBINDIR}/fppd ]; then
   echo "${FPPBINDIR}/fppd doesn't exist, try building it"
   cleanCompiledBinaries
   compileBinaries
fi

# Clear any restart flag
sed -i -e "s/^restartFlag .*/restartFlag = 0/" ${FPPHOME}/media/settings

echo "Setup channel outputs"
setupChannelOutputs

echo "Running pre-start scripts"
runPreStartScripts

##############################################################################
# Leave these things till last so user can see output of anything above here
##############################################################################
applyScreenBlankSetting
