#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common
. ${BINDIR}/functions

cd ${FPPDIR}

logOutput

# Clear any restart flag
sed -i -e "s/^restartFlag .*/restartFlag = 0/" ${FPPHOME}/media/settings

updateAvahiConfig

setupChannelOutputs

runPreStartScripts


WaitForInterfacesUp() {
IPS="$(ip -o -4 addr | grep -v usb | grep -v 127.0)"
   #echo "x:  $IPS" >> /tmp/ips.txt
if [ -z "$IPS" ]; then
    # Loop up to 8 times, so max wait time is 8 * 2
    for i in {1..8}
    do
	sleep 2
        IPS="$(ip -o -4 addr | grep -v usb | grep -v 127.0)"
	#echo "y:  $IPS" >> /tmp/ips.txt
        if [ -z "$IPS" ]
        then
            continue
        fi

        break
    done
fi

#turn off power management on wireless... not all adapters
# support this so just /dev/null any output
iwconfig wlan0 power off 2>/dev/null >/dev/null
}

WaitForInterfacesUp



echo "Starting ${FPPBINDIR}/fppd"
nice -n -20 ${FPPBINDIR}/fppd --config-file ${FPPHOME}/media/settings --daemonize

# FIXME, find a better way to wait until fppd is up before continuing
sleep 2

startWebSocketServer

runPostStartScripts

