#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common
. ${BINDIR}/functions

# Make sure a UUID file exists
${BINDIR}/get_uuid > /dev/null

# Clear any restart flag
sed -i -e "s/^restartFlag .*/restartFlag = 0/" ${FPPHOME}/media/settings

echo "Setup channel outputs"
setupChannelOutputs

echo "Running pre-start scripts"
runPreStartScripts

##############################################################################
# Leave these things till last so user can see output of anything above here
##############################################################################
applyScreenBlankSetting
