#!/bin/bash

PLATFORM=$(uname);

if [ "$PLATFORM" = "Darwin" ]; then
    PATH=$PATH:/usr/sbin:/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:
    ioreg -d2 -c IOPlatformExpertDevice | awk -F\" '/IOPlatformUUID/{print $(NF-1)}'
    exit 0
fi


#
# Check for an developer-only FPP_UUID setting
#

UUID=$(grep "^FPP_UUID" /home/fpp/media/settings | cut -f2 -d= | sed -e "s/[^-A-Z0-9]//g")
if [ "$UUID" != "" ]; then
    echo "$UUID"
    exit 0
fi

#
# Try and use CPUInfo -- works on PI and BBB
#
UUID=$(grep -i serial /proc/cpuinfo | awk '{ print $3}')
if [ "$UUID" != "" ] && [ "$UUID" != "0" ]; then
    echo "M1-$UUID"
    exit 0
fi

if [ -f "/proc/device-tree/serial-number" ]; then
    UUID=$(tr -d '\0' </proc/device-tree/serial-number)
    echo "M3-$UUID"
    exit 0
fi

if [ -f "/sys/bus/i2c/devices/0-0050/eeprom" ]; then 
    sn=$(dd if=/sys/bus/i2c/devices/0-0050/eeprom count=16 skip=40 bs=1 2>/dev/null || true)
    if [[ "$sn" =~ ^[0-9]*PB2[0-9A-F]*$ ]]; then
        echo "M5-$sn"
        exit 0
    fi
fi


#
# Try dmidecode
#
if [[ -f /sbin/dmidecode  || -f /usr/sbin/dmidecode ]]; then
    UUID=$(sudo dmidecode | grep -i 'serial number'| head -1 | awk '{print $3}')
    if [[ "$UUID" =~ ^\$\(.* ]]; then
        UUID=$(sudo dmidecode | grep -i 'UUID' | head -1 | awk '{print $2}')
    fi
    if [ "$UUID" == "" ] || [ "$UUID" == "0" ] || [ "$UUID" == "Serial" ] || [ "$UUID" == "123456789" ] || [[ "$UUID" =~ ^00*0 ]]; then
        UUID=$(sudo dmidecode | grep -i 'UUID' | head -1 | awk '{print $2}')
    fi
    if [ "$UUID" != "" ] && [ "$UUID" != "0" ]; then
        echo "M2-$UUID"
        exit 0
    fi
fi


if [ -f "/etc/machine-id" ]; then
    UUID=$(tr -d '\0' </etc/machine-id)
    echo "M4-$UUID"
    exit 0
fi

#
# If all else fails, Genereate one
#
UUIDFILE="/etc/fpp/fpp_uuid"
if [ ! -f $UUIDFILE ]; then
    sudo cp /proc/sys/kernel/random/uuid $UUIDFILE
    sudo chmod 644 $UUIDFILE
fi;

cat $UUIDFILE
