#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common
. ${BINDIR}/functions

logOutput

# Ensure newfeatures remote exists
cd ${FPPDIR}
if ! git remote get-url newfeatures > /dev/null 2>&1; then
	if [ "x${FPPDIR}" = "x/opt/fpp" ]; then
		$SUDO git remote add newfeatures https://github.com/FalconChristmas/fpp-new-feature-testing.git
	else
		sudo -u ${FPPUSER} git remote add newfeatures https://github.com/FalconChristmas/fpp-new-feature-testing.git
	fi
fi

if curl --silent --head https://github.com | grep -i "Content-Type: text/html; charset=utf-8" >/dev/null; then
	GITBRANCH=$(cd ${FPPDIR} && git branch | grep "^\*" | sed -e "s/\*\s//")

	# Hold the shared git repo lock so this background fetch can't write
	# FETCH_HEAD (or contend on ref locks) while an upgrade's fetch/rebase is
	# running -- see runGitLocked in scripts/functions.
	if [ "x${FPPDIR}" = "x/opt/fpp" ]
	then
		runGitLocked "cd ${FPPDIR} && git fetch -p -P && git fetch --tags -f && git submodule foreach git fetch -p -P"
	else
		runGitLocked "cd ${FPPDIR} && sudo -u ${FPPUSER} git fetch -p -P && sudo -u ${FPPUSER} git submodule foreach git fetch -p -P"
	fi

else
	echo "Can not access github, unable to fetch git updates"
fi

