#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common
. ${BINDIR}/functions

if [ "x$1" = "x" ]
then
	echo "USAGE: $0 BRANCHNAME"
	exit 1
fi

logOutput

echo "$0 running to switch branches to $1"

echo "Stopping fppd"
${SUDO} ${FPPDIR}/scripts/fppd_stop

remountRootReadWrite

echo "Cleaning up any compiled binaries"
cleanCompiledBinaries

echo "Switching git branch to $1"
if [ "x${FPPDIR}" = "x/opt/fpp" ]
then
	cd ${FPPDIR} && $SUDO git clean -df && $SUDO git checkout $1 && $SUDO git pull && $SUDO git submodule sync && $SUDO git submodule update --init
else
	cd ${FPPDIR} && sudo git clean -df && sudo -u ${FPPUSER} git checkout $1 && sudo -u ${FPPUSER} git pull && sudo -u ${FPPUSER} git submodule sync && sudo git submodule update --init
fi

# Compile binaries if not running a release branch
RELEASEBRANCH=$(echo $1 | egrep "v[0-9]+\.[0-9]+")
if [ -z "${RELEASEBRANCH}" ] || [ "x${FPPPLATFORM}" == "xLinux" ]
then
	echo "Compiling Binaries"
	compileBinaries
fi

remountRootReadOnlyIfNeeded

echo "Restarting fppd"
${SUDO} ${FPPDIR}/scripts/fppd_start

