#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common
. ${BINDIR}/functions

teeOutput

if curl --silent --head https://github.com | grep "Content-Type: text/html; charset=utf-8" >/dev/null; then
	GITBRANCH=$(cd ${FPPDIR} && git branch | grep "^\*" | sed -e "s/\*\s//")

	echo "Upgrading git revision from branch ${GITBRANCH}"

	remountRootReadWrite

	if [ "x${FPPDIR}" = "x/opt/fpp" ]
	then
		cd ${FPPDIR} && $SUDO git pull && $SUDO git fetch --tags && $SUDO git submodule sync && $SUDO git submodule update --init
	else
		cd ${FPPDIR} && sudo -u ${FPPUSER} git pull && sudo -u ${FPPUSER} git fetch --tags && sudo -u ${FPPUSER} git submodule sync && sudo -u ${FPPUSER} git submodule update --init
	fi

	RELEASEBRANCH=$(echo ${GITBRANCH} | egrep "v[0-9]+\.[0-9]+")
	if [ -z "${RELEASEBRANCH}" ] || [ "x${FPPPLATFORM}" == "xLinux" ]
	then
	    #make sure all scripts are executable
	    sudo chmod 755 -R ${UPGRADEDIR}
	    #run config upgrade
		sudo ${SCRIPTDIR}/upgrade_config

		compileBinaries
	fi

	remountRootReadOnlyIfNeeded
else
	echo "Can not access github, unable to pull git updates"
fi

