#!/bin/sh

BINDIR=$(dirname $0)
. ${BINDIR}/common

if [ "x$1" = "x" ]
then
	echo "USAGE: $0 BRANCHNAME"
	exit 1
fi

logOutput

echo "Switching git branch to $1"
cd ${FPPDIR} && sudo -u pi git checkout $1

