#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common

if [ "x${FPPDIR}" = "x/opt/fpp" ]
then
	cd ${FPPDIR} && $SUDO git reset --hard HEAD
else
	cd ${FPPDIR} && sudo -u pi git reset --hard HEAD
fi

