#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common

if [ "x$1" = "x" ] || [ "x$2" = "x" ] || [ "x$3" = "x" ]
then
	echo "USAGE: $0 PLUGINNAME GITURL SHA1"
	exit 1
fi

logOutput

echo "Installing plugin $1"
if [ "x${FPPDIR}" = "x/opt/fpp" ] && [ "x${SETTINGSFILE}" = "x${FPPHOME}/media/settings" ]
then
	cd ${PLUGINDIR} && $SUDO git clone $2 $1
	cd $1 && $SUDO git reset --hard $3
elif [ "x${FPPDIR}" = "x${FPPHOME}/fpp" ]
then
	cd ${PLUGINDIR} && sudo -u pi git clone $2 $1
	cd $1 && sudo -u pi git reset --hard $3
else
	cd ${PLUGINDIR} && git clone $2 $1
	cd $1 && git reset --hard $3
fi


if [ -x "${PLUGINDIR}/$1/fpp_install.sh" ]
then
	if [ "x${FPPDIR}" = "x/opt/fpp" ] && [ "x${SETTINGSFILE}" = "x${FPPHOME}/media/settings" ]
	then
		$SUDO ${PLUGINDIR}/$1/fpp_install.sh
	elif [ "x${FPPDIR}" = "x${FPPHOME}/fpp" ]
	then
		sudo -u pi ${PLUGINDIR}/$1/fpp_install.sh
	else
		${PLUGINDIR}/$1/fpp_install.sh
	fi
fi
