#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common
. ${BINDIR}/functions

forceLocalAudio=$(getSetting forceLocalAudio)

FORCEAUDIO=
if [ "x${forceLocalAudio}" = "x1" ]
then
	FORCEAUDIO="-o local"
fi

/usr/bin/omxplayer -i "$1" 2>&1 | grep Duration:

exec /usr/bin/omxplayer ${FORCEAUDIO} -s "$1" 2>&1

