#!/bin/bash
#
# piRTC
#
# Setup RTC
#
#

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common
. ${BINDIR}/functions

if [ "${FPPPLATFORM}" = "Raspberry Pi" ]
then
	setupPiRTC
fi

if [[ $1 == "set" ]]
then
  hwclock -w &>/dev/null
else
  hwclock -s &>/dev/null
  cp /opt/fpp/etc/update-RTC /etc/cron.daily/
fi

sleep 2

