#!/bin/bash
#
# startup
#
# Called from rc.local to start FPP
#
#

BINDIR=$(dirname $0)
. ${BINDIR}/common

amixer cset numid=3 1
ORIGVOLUME=$(getSetting volume)
VOLUME=$(expr ${ORIGVOLUME} / 2 + 50)
amixer set PCM ${VOLUME}%

# Print/Say the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
  arrHost=(${_IP// / })
  flite -voice kal "I Have Found The Following I P Addresses, ${arrHost[0]}, ${arrHost[1]},  ${arrHost[2]}"
fi

# Check for flash drive mounted
while [ true ]
do
if [ "$(df -h ${MEDIADIR} | tail -n 1 | awk '{print $1}')" == "$(df -h / | tail -n 1 | awk '{print $1}')" ];
then
        echo "Flash Media Is Missing.  Please Insert.";
        flite -voice kal "Boot Stalled, Flash Media Is Missing.  Please Insert."
        sleep 20;
        mount -a;

else
        echo "Flash Media Mounted.";
        mkdir -p /home/pi/media/logs
        break
fi
done

sysctl net/ipv4/igmp_max_memberships=150
/usr/local/bin/gpio load spi 100
setterm -blank 1
# mpg123 ${FPPDIR}/bin/silence.mp3 > /dev/null

sed -e "s#FPPDIR#${FPPDIR}#g" < ${FPPDIR}/etc/apache2.site > /etc/apache2/sites-available/default
/etc/rc2.d/S02apache2 restart

${BINDIR}/piRTC

${BINDIR}/fpp_boot

PiLCDenabled=$(awk -f ${FPPDIR}/scripts/readSetting.awk /home/pi/media/settings setting=PI_LCD_Enabled)
echo $PiLCDenabled

if [[ $PiLCDenabled == "true" ]]
then
  echo "LCD Enabled"
  ${FPPDIR}/scripts/lcd/fppLCD start
else
  echo "LCD Disabled"
fi

