#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common

if [ ! -d ${LOGDIR} ]
then
	mkdir -p ${LOGDIR}
	chown ${FPPUSER}.${FPPUSER} ${LOGDIR}
	chmod 775 ${LOGDIR}
fi

if [ ! -f "${MEDIADIR}/timezone" ]
then
	cp /etc/timezone ${MEDIADIR}/timezone
	chown ${FPPUSER}.${FPPUSER} ${MEDIADIR}/timezone
	exit 0
fi

if [ "x$(cat /etc/timezone)" != "x$(cat ${MEDIADIR}/timezone)" ]
then
    if [ -f "/usr/bin/timedatectl" ]
    then
        ${SUDO} timedatectl set-timezone `cat ${MEDIADIR}/timezone`
    else
        ${SUDO} cp ${MEDIADIR}/timezone /etc/timezone
        ${SUDO} dpkg-reconfigure -f noninteractive tzdata
    fi
fi
