#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common

if [ "x$1" = "x" ]
then
	echo "USAGE: $0 PLUGINNAME"
	exit 1
fi

logOutput

if [ -x "${FPPDIR}/plugins/$1/fpp_uninstall.sh" ]
then
	if [ "x${FPPDIR}" = "x/opt/fpp" ] && [ "x${SETTINGSFILE}" = "x/home/pi/media/settings" ]
	then
		sudo ${FPPDIR}/plugins/$1/fpp_uninstall.sh
	elif [ "x${FPPDIR}" = "x/home/pi" ]
	then
		sudo -u pi ${FPPDIR}/plugins/$1/fpp_uninstall.sh
	else
		${FPPDIR}/plugins/$1/fpp_uninstall.sh
	fi
fi

echo "Uninstalling plugin $1"
if [ "x${FPPDIR}" = "x/opt/fpp" ] && [ "x${SETTINGSFILE}" = "x/home/pi/media/settings" ]
then
	cd ${FPPDIR}/plugins && [ -d $1 ] && sudo rm -rf $1
elif [ "x${FPPDIR}" = "x/home/pi" ]
then
	cd ${FPPDIR}/plugins && [ -d $1 ] && sudo -u pi rm -rf $1
else
	cd ${FPPDIR}/plugins && [ -d $1 ] && rm -rf $1
fi

