<h3>Developer</h3>
<p>Visible only when <b>User Interface Level = Developer</b>. These affect how FPP is built and which branch it tracks. For daily shows leave them alone — they can erase untracked files and recompile for minutes.</p>

<h4>Settings on this tab</h4>
<ul>
    <li><b>UI Platform Masq</b> (dropdown) — Makes the UI pretend to be a different platform to test layout without that hardware. Options: Default, Raspberry Pi, BeagleBone Black/64, CHIP, Armbian, Debian, FreeBSD, Linux, ODROID, OrangePi, Pine64, PogoPlug, qemu, Ubuntu. Reloads the UI. Does not change actual hardware detection, so hardware-specific setup may still not work.</li>
    <li><b>Git Remote Repository</b> (dropdown, Developer) — Which git remote branch listing tracks: <b>FPP Releases</b> = <code>origin</code> (stable), <b>FPP New Feature Testing</b> = <code>newfeatures</code> (experimental), <b>Pull Requests</b> = <code>pull-requests</code> (open PRs on <code>FalconChristmas/fpp</code> via <code>api/git/pullRequests</code>). Changing the remote reloads the Branch dropdown via <code>api/git/branches?remote=</code> or <code>api/git/pullRequests</code> for PR mode.</li>
    <li><b>GitHub User Name</b> (text, pii, Developer) — GitHub username paired with the token below for private plugin repos. Used only when <i>Use Credentials</i> is selected in Plugin Manager.</li>
    <li><b>GitHub Personal Access Token</b> (password, Developer) — Classic or fine-grained PAT with read access to your private repos. Stored in <code>/home/fpp/media/settings</code>. Same usage as above.</li>
    <li><b>Distributed Compile</b> (dropdown, Developer) — Offload FPP rebuilds to a helper. Options: <b>Off</b>, <b>distcc</b>, <b>distcc + zeroconf</b> (auto-discovered), <b>nocc</b>, <b>nocc + mdns</b> (recommended for slow boards; helper set up via <code>scripts/setup_nocc_host.sh</code> or <code>scripts/setup_distcc_host.sh</code>). Any distributed mode disables the precompiled header and requires matching compiler majors. Helper is named in <i>Compile Hosts</i> below except for zeroconf/mdns modes.</li>
    <li><b>Compile Hosts</b> (text, pii, Developer) — Space-separated helper list. distcc form: <code>host[:port][/jobs][,options]</code> (e.g. <code>myhelper:3632/6,lzo</code>); nocc form: <code>host[:port]</code> (default 43210). Ignored for zeroconf/mdns discovery.</li>
    <li><b>Git Branch</b> (dropdown) — Branches from the selected remote (<code>git fetch -p --all</code> + <code>git branch -r</code> filtered by <code>filterBranch()</code> that hides v0–v4, cpinkham/dkulp private branches, new-ui and stage) or, when <b>Pull Requests</b> is selected above, open PRs listed as <code>#&lt;num&gt; - &lt;user&gt;</code> (up to 60 chars, draft flagged <code>[Draft]</code>, all PRs via <code>api/git/pullRequests</code>). Selecting a PR fetches <code>origin pull/&lt;num&gt;/head</code> and checks out a local branch <code>pr-&lt;num&gt;</code>. Changing branches/PRs streams to the upgrade handler (pull + recompile) — may take minutes and <b>runs <code>git clean -df</code> removing untracked files</b>. Back up development work first. If the chosen PR carries a config migration this device has not run (an <code>upgrade/&lt;n&gt;</code> above <code>/etc/fpp/config_version</code>), the switch stops on a confirmation screen listing them: <code>upgrade_config</code> only moves the config version <b>forward</b>, the migrations change the system outside git (packages, systemd units, Apache/FPP config), and switching back to a release branch undoes none of it. PRs branched from the same point also reuse the same migration number, so running one PR's <code>upgrade/&lt;n&gt;</code> makes every other PR's — and the released one — skip on this device. Only continue on a device you are willing to reflash.</li>
    <li><b>Git Status / Reset Local Changes</b> (panel + button) — Shows <code>api/git/status</code> log. <b>Reset Local Changes</b> calls <code>api/git/reset</code> = <code>git reset --hard HEAD</code> wiping local source edits.</li>
    <li><b>FPP Rebuild</b> (button) — Recompiles local sources (<code>RebuildFPPSource()</code>). Warning: may take minutes.</li>
</ul>

<p><b>Safety tips:</b> Do not switch branches or rebuild while a show is running. If you edited source in <code>src/</code>, commit or back it up before using any button on this tab.</p>
