/*
 * This file is part of the Falcon Player (FPP) and is Copyright (C)
 * 2013-2022 by the Falcon Player Developers.
 *
 * The Falcon Player (FPP) is free software, and is covered under
 * multiple Open Source licenses.  Please see the included 'LICENSES'
 * file for descriptions of what files are covered by each license.
 *
 * This source file is covered under the GPL v2 as described in the
 * included LICENSE.GPL file.
 */

#include "fpp-pch.h"

#include "fpp-json.h"

#ifdef PLATFORM_OSX
#include <sys/event.h>
#define USE_KQUEUE
#else
#include <sys/epoll.h>
#include <sys/prctl.h>
#include <sys/sysinfo.h>
#include <syscall.h>
#endif

#include <Magick++/Image.h>
#include <curl/curl.h>
#include <magick/magick.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <chrono>
#include <cstdlib>
#include <ctime>
#include <errno.h>
#include <execinfo.h>
#include <fcntl.h>
#include <filesystem>
#include <fstream>
#include <functional>
#include <getopt.h>
#include <iostream>
#include <map>
#include <set>
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <string>
#include <thread>
#include <unistd.h>
#include <utility>

#include "common.h"
#include "log.h"
#include "mqtt.h"
#include "settings.h"

#include "CurlManager.h"
#include "EPollManager.h"
#include "Events.h"
#include "FileMonitor.h"
#include "FPPLocale.h"
#include "MultiSync.h"
#include "NetworkMonitor.h"
#include "OutputMonitor.h"
#include "RecurringTasks.h"
#include "Player.h"
#include "Plugins.h"
#include "Scheduler.h"
#include "Sequence.h"
#include "Timers.h"
#include "Variables.h"
#include "Warnings.h"
#include "command.h"
#include "e131bridge.h"
#include "effects.h"
#include "fppversion.h"
#include "gpio.h"
#include "httpAPI.h"
#include "ping.h"
#include "channeloutput/ChannelOutputSetup.h"
#include "channeloutput/channeloutputthread.h"
#include "channeltester/ChannelTester.h"
#include "commands/Commands.h"
#include "commands/IfCommand.h"
#include "mediaoutput/AES67Manager.h"
#include "mediaoutput/OpusRTPManager.h"
#include "mediaoutput/MediaOutputBase.h"
#include "mediaoutput/MediaOutputStatus.h"
#include "mediaoutput/VideoInputManager.h"
#include "mediaoutput/VideoOutputManager.h"
#include "mediaoutput/mediaoutput.h"
#include "overlays/PixelOverlay.h"
#include "playlist/Playlist.h"
#include "sensors/Sensors.h"
#include "util/GPIOUtils.h"
#include "util/TmpFileGPIO.h"

#include "MDNSManager.h"
#include "WLEDAPIResponder.h"
#include "WLEDAudioSync.h"

#include "fppd.h"

#if defined(PLATFORM_BBB) || defined(PLATFORM_BB64)
#include "util/BBBUtils.h"
#define PLAT_GPIO_CLASS BBBPinProvider
#elif defined(PLATFORM_PI)
#include "util/PiGPIOUtils.h"
#define PLAT_GPIO_CLASS PiGPIOPinProvider
#elif defined(GPIOD_CHIPS) && GPIOD_CHIPS > 0
#define PLAT_GPIO_CLASS NoPinCapabilitiesProvider
#else
#include "util/TmpFileGPIO.h"
#define PLAT_GPIO_CLASS TmpFilePinProvider
#endif

pid_t pid, sid;
volatile int runMainFPPDLoop = 1;
volatile bool restartFPPD = 0;

/* Prototypes for functions below */
void MainLoop(void);
void PublishStatsBackground(std::string reason);
void PublishStatsForce(std::string reason);

static int IsDebuggerPresent() {
    char buf[1024];
    int debugger_present = 0;

    int status_fd = open("/proc/self/status", O_RDONLY);
    if (status_fd == -1) {
        return 0;
    }
    ssize_t num_read = read(status_fd, buf, sizeof(buf) - 1);
    if (num_read > 0) {
        static const char TracerPid[] = "TracerPid:";
        char* tracer_pid;

        buf[num_read] = 0;
        tracer_pid = strstr(buf, TracerPid);
        if (tracer_pid) {
            debugger_present = !!atoi(tracer_pid + sizeof(TracerPid) - 1);
        }
    }
    return debugger_present;
}

// Try to attach gdb to print stack trace (Linux only).
// The sole purpose is to improve the very poor stack traces generated by backtrace() on ARM platforms
// Sets *reason to a short constant describing why no gdb stack was produced.
// Recorded in the crash report because "symbol-only stack, no line numbers" is
// otherwise indistinguishable between causes -- gdb missing, gdb timing out,
// ptrace refused, or fork() failing under memory pressure all look identical
// downstream, and they call for completely different remedies.
static bool dumpstack_gdb(const char** reason = nullptr) {
    // The watchdog callers only want the side effect of dumping a stack; only
    // the crash handler records why it failed.
    const char* ignored = nullptr;
    if (!reason) {
        reason = &ignored;
    }
    *reason = "unknown";
#ifndef PLATFORM_OSX
    char pid_buf[30];
    snprintf(pid_buf, sizeof(pid_buf), "%d", getpid());
    char thread_buf[30];
    snprintf(thread_buf, sizeof(thread_buf), "(LWP %ld)", syscall(__NR_gettid));
    char name_buf[512];
    name_buf[readlink("/proc/self/exe", name_buf, 511)] = 0;

    constexpr static int kTimeoutSec = 30;

    if (IsDebuggerPresent()) {
        *reason = "a debugger is already attached";
        return false;
    }
    (void)remove("/tmp/fppd_crash.log");

    // Allow us to be traced
    // Note: Does not currently work in WSL: https://github.com/Microsoft/WSL/issues/3053
    int retval = prctl(PR_SET_PTRACER, PR_SET_PTRACER_ANY, 0, 0, 0);
    const bool ptraceSetFailed = (retval != 0);

    // Spawn helper process which will keep running when gdb is attached to main domoticz process
    pid_t intermediate_pid = fork();
    if (intermediate_pid == -1) {
        // Overwhelmingly ENOMEM on a 480MB BeagleBone, or a crash that left the
        // process unable to fork.
        *reason = "fork() for the gdb helper failed";
        return false;
    }
    if (!intermediate_pid) {
        // Wathchdog 1: Used to kill sub processes to gdb which may hang
        pid_t timeout_pid1 = fork();
        if (timeout_pid1 == -1) {
            _Exit(1);
        }
        if (timeout_pid1 == 0) {
            sleep(kTimeoutSec);
            _Exit(1);
        }

        // Wathchdog 2: Give up on gdb, if it still does not finish even after killing its sub processes
        pid_t timeout_pid2 = fork();
        if (timeout_pid2 == -1) {
            kill(timeout_pid1, SIGKILL);
            _Exit(1);
        }
        if (timeout_pid2 == 0) {
            sleep(kTimeoutSec + 10);
            _Exit(1);
        }

        // Worker: Spawns gdb
        pid_t worker_pid = fork();
        if (worker_pid == -1) {
            kill(timeout_pid1, SIGKILL);
            kill(timeout_pid2, SIGKILL);
            _Exit(1);
        }
        if (worker_pid == 0) {
            (void)remove("/tmp/fppd_crash.log");
            int fd = open("/tmp/fppd_crash.log", O_WRONLY | O_CREAT | O_TRUNC, S_IRUSR | S_IWUSR);
            if (fd == -1)
                _Exit(1);
            if (dup2(fd, STDOUT_FILENO) == -1)
                _Exit(1);
            if (dup2(fd, STDERR_FILENO) == -1)
                _Exit(1);
            execlp("gdb", "gdb", "--batch", "-n", "-ex", "thread apply all bt", "-ex", "info threads", "-ex", "bt", "-ex", "detach", name_buf, pid_buf, NULL);

            // If gdb failed to start, signal back
            close(fd);
            _Exit(1);
        }

        int result = 1;

        // Wait for all children to die
        while (worker_pid || timeout_pid1 || timeout_pid2) {
            int status = 0;
            // pid_t exited_pid = wait(&status);
            usleep(100000);
            // printf("pid worker_pid: %d, timeout_pid1: %d, timeout_pid2: %d\n", worker_pid, timeout_pid1, timeout_pid2);
            if (worker_pid && waitpid(worker_pid, &status, WNOHANG)) {
                worker_pid = 0;
                // printf("Status: %x, wifexited: %u, wexitstatus: %u\n", status, WIFEXITED(status), WEXITSTATUS(status));
                // printf("Sending SIGKILL to timeout_pid1\n");
                if (timeout_pid1)
                    kill(timeout_pid1, SIGKILL);
                if (timeout_pid2)
                    kill(timeout_pid2, SIGKILL);
            } else if (timeout_pid1 && waitpid(timeout_pid1, &status, WNOHANG)) {
                // Watchdog 1 timed out, attempt to recover by killing all gdb's child processes
                char tmp[128];
                timeout_pid1 = 0;
                // printf("Sending SIGKILL to worker_pid's children\n");
                if (worker_pid) {
                    snprintf(tmp, sizeof(tmp), "pkill -KILL -P %d", worker_pid);
                    int ret = system(tmp);
                }
            } else if (timeout_pid2 && waitpid(timeout_pid2, &status, WNOHANG)) {
                // Watchdog 2 timed out, give up
                timeout_pid2 = 0;
                // printf("Sending SIGKILL to worker_pid\n");
                if (worker_pid)
                    kill(worker_pid, SIGKILL);
                if (timeout_pid1)
                    kill(timeout_pid1, SIGKILL);
            }
        }
        _Exit(result); // Or some more informative status
    } else {
        int status = 0;
        pid_t res = waitpid(intermediate_pid, &status, 0);
        if (FileExists("/tmp/fppd_crash.log")) {
            std::string s = GetFileContents("/tmp/fppd_crash.log");
            if (s != "") {
                LogErr(VB_ALL, "Stack: \n%s\n", s.c_str());
                // printf("%s\n", s.c_str());
                return true;
            }
            *reason = ptraceSetFailed
                          ? "gdb produced no output and PR_SET_PTRACER was refused"
                          : "gdb produced no output (not installed, exec failed, or watchdog timeout)";
        } else {
            *reason = ptraceSetFailed
                          ? "gdb wrote no stack file and PR_SET_PTRACER was refused"
                          : "gdb wrote no stack file (not installed, exec failed, or watchdog timeout)";
        }
    }
#endif
    return false;
}

static const char* safe(const char* in) {
    return in ? in : "<NULL>";
}

// ──────────────────────────────────────────────────────────────────────────
// Async-signal-safe crash-report primitives.
//
// Only write() and pure arithmetic -- no allocation, no locks, no stdio.  A
// fatal signal that fires while this thread holds the malloc arena lock (a
// heap-corruption SIGABRT raised from inside free() always does) turns any
// allocating call into a self-deadlock, and that is the same condition most
// likely to have made gdb's fork() fail and dropped us onto the fallback path
// in the first place.  So the machine-readable record is emitted with these
// first, and anything that can allocate is attempted only afterwards.
// ──────────────────────────────────────────────────────────────────────────
static void safeWrite(int fd, const char* str) {
    if (fd < 0 || !str) {
        return;
    }
    (void)!write(fd, str, strlen(str));
}

static void safeWriteHex(int fd, uintptr_t val) {
    char buf[2 + sizeof(uintptr_t) * 2 + 1];
    char* p = buf + sizeof(buf) - 1;
    *p = '\0';
    if (val == 0) {
        *--p = '0';
    }
    while (val) {
        *--p = "0123456789abcdef"[val & 0xF];
        val >>= 4;
    }
    *--p = 'x';
    *--p = '0';
    safeWrite(fd, p);
}

static void safeWriteReg(int fd, const char* name, uintptr_t val) {
    safeWrite(fd, name);
    safeWrite(fd, "=");
    safeWriteHex(fd, val);
    safeWrite(fd, " ");
}

// Registers at the fault, taken from the signal's ucontext.
//
// This is the one piece of evidence that survives when the unwinder cannot
// walk the stack at all.  Crashes inside a hand-written-assembly libc routine
// (Raspberry Pi preloads libarmmem's memcpy over glibc's) report a single
// frame and nothing else, because that code carries no unwind tables -- so the
// caller is unrecoverable by backtrace() no matter how fppd itself is
// compiled.  The link register still holds the return address into the caller,
// and the argument registers still hold what was passed, which for a faulting
// memcpy is the destination, source and length that caused it.
static void safeWriteFaultRegisters(int fd, void* ctx) {
    if (!ctx) {
        return;
    }
    safeWrite(fd, "\n=== registers at fault ===\n");
// Keyed on __linux__ rather than the FPP platform defines: these are glibc's
// ucontext layouts, and every other libc spells them differently.
#if defined(__linux__) && defined(__aarch64__)
    const ucontext_t* uc = (const ucontext_t*)ctx;
    safeWriteReg(fd, "pc", (uintptr_t)uc->uc_mcontext.pc);
    safeWriteReg(fd, "sp", (uintptr_t)uc->uc_mcontext.sp);
    safeWriteReg(fd, "lr", (uintptr_t)uc->uc_mcontext.regs[30]);
    safeWrite(fd, "\n");
    for (int i = 0; i < 8; i++) {
        char nm[4] = { 'x', (char)('0' + i), '\0', '\0' };
        safeWriteReg(fd, nm, (uintptr_t)uc->uc_mcontext.regs[i]);
    }
    safeWrite(fd, "\n");
#elif defined(__linux__) && defined(__arm__)
    const ucontext_t* uc = (const ucontext_t*)ctx;
    safeWriteReg(fd, "pc", (uintptr_t)uc->uc_mcontext.arm_pc);
    safeWriteReg(fd, "sp", (uintptr_t)uc->uc_mcontext.arm_sp);
    safeWriteReg(fd, "lr", (uintptr_t)uc->uc_mcontext.arm_lr);
    safeWrite(fd, "\n");
    safeWriteReg(fd, "r0", (uintptr_t)uc->uc_mcontext.arm_r0);
    safeWriteReg(fd, "r1", (uintptr_t)uc->uc_mcontext.arm_r1);
    safeWriteReg(fd, "r2", (uintptr_t)uc->uc_mcontext.arm_r2);
    safeWriteReg(fd, "r3", (uintptr_t)uc->uc_mcontext.arm_r3);
    safeWrite(fd, "\n");
#elif defined(__linux__) && defined(__x86_64__)
    const ucontext_t* uc = (const ucontext_t*)ctx;
    safeWriteReg(fd, "rip", (uintptr_t)uc->uc_mcontext.gregs[REG_RIP]);
    safeWriteReg(fd, "rsp", (uintptr_t)uc->uc_mcontext.gregs[REG_RSP]);
    safeWrite(fd, "\n");
    safeWriteReg(fd, "rdi", (uintptr_t)uc->uc_mcontext.gregs[REG_RDI]);
    safeWriteReg(fd, "rsi", (uintptr_t)uc->uc_mcontext.gregs[REG_RSI]);
    safeWriteReg(fd, "rdx", (uintptr_t)uc->uc_mcontext.gregs[REG_RDX]);
    safeWrite(fd, "\n");
#else
    (void)ctx;
    safeWrite(fd, "(register dump not implemented for this architecture)\n");
#endif
}

// Copy /proc/self/maps verbatim.  Without the load address of each module, the
// raw frame addresses below are meaningless off-box: the report side needs
// (address - module base) to run addr2line against a stashed build.
static void safeWriteModuleMap(int fd) {
#ifndef PLATFORM_OSX
    safeWrite(fd, "\n=== module map (/proc/self/maps) ===\n");
    int mfd = open("/proc/self/maps", O_RDONLY);
    if (mfd < 0) {
        safeWrite(fd, "(unavailable)\n");
        return;
    }
    char buf[4096];
    ssize_t n;
    while ((n = read(mfd, buf, sizeof(buf))) > 0) {
        (void)!write(fd, buf, (size_t)n);
    }
    close(mfd);
#else
    safeWrite(fd, "\n=== module map unavailable on this platform ===\n");
#endif
}

static void handleCrash(int s, siginfo_t* si, void* ctx) {
    static volatile bool inCrashHandler = false;
    if (inCrashHandler) {
        // need to ignore any crashes in the crash handler
        return;
    }
    inCrashHandler = true;
    // Everything this handler logs from here on -- the signal line, the gdb
    // stack -- would otherwise push the pre-crash history out of the ring.
    CrashLogRingFreeze();
    if (s != SIGQUIT && s != SIGUSR1) {
        // Wedge-proofing: nearly everything below is async-signal-UNSAFE —
        // fork()/gdb, LogErr (malloc), system()/curl.  When the fatal signal
        // fired while this thread held a libc lock (a heap-corruption SIGABRT
        // inside free() always does), any of it can self-deadlock; the process
        // then hangs forever, systemd keeps seeing it as running, and
        // Restart=always never fires.  Arm a watchdog with SIGALRM restored to
        // its default (terminate) disposition — both calls are
        // async-signal-safe — so a wedged handler still dies and gets
        // restarted.  Normal paths finish in exit(-1) long before it fires;
        // the timeout is generous because the crash-report zip + curl upload
        // legitimately take time.  Left armed across exit(-1) on purpose:
        // atexit/global destructors can hit the same held locks.
        constexpr unsigned int kCrashHandlerWatchdogSec = 120;
        struct sigaction almAct;
        memset(&almAct, 0, sizeof(almAct));
        almAct.sa_handler = SIG_DFL;
        sigemptyset(&almAct.sa_mask);
        sigaction(SIGALRM, &almAct, nullptr);
        alarm(kCrashHandlerWatchdogSec);
    }
    int crashLog = getSettingInt("ShareCrashData", 3);
#ifndef PLATFORM_OSX
    LogErr(VB_ALL, "Crash handler called in thread %u:  signal=%d (SIG%s: %s) addr=%p si_code=%d\n",
           gettid(), s, safe(sigabbrev_np(s)), safe(sigdescr_np(s)),
           si ? si->si_addr : nullptr, si ? si->si_code : -1);
#else
    uint64_t tid;
    pthread_threadid_np(NULL, &tid);
    LogErr(VB_ALL, "Crash handler called in thread %u:  signal=%d addr=%p\n", tid, s, si ? si->si_addr : nullptr);
#endif

    // Deliberately the raw member, not GetSeqFilenameCopy(): this is a signal
    // handler, so it can interrupt a thread that already holds m_seqFilenameLock
    // and taking it here would self-deadlock the crash report.  A torn read is
    // the acceptable trade for a log line that is already best-effort.
    if (!sequence->m_seqFilename.empty()) {
        LogErr(VB_ALL, "   while playing  %s  at  %d ms\n", sequence->m_seqFilename.c_str(), sequence->m_seqMSElapsed);
    }
    const char* gdbFailReason = nullptr;
    if (!dumpstack_gdb(&gdbFailReason)) {
        void* callstack[128];
        int i, frames = backtrace(callstack, 128);
        int fd = open("/tmp/fppd_crash.log", O_WRONLY | O_CREAT | O_TRUNC, S_IRUSR | S_IWUSR);

        // Safe half first (see the safeWrite* helpers): the reason, the raw
        // return addresses and the module map are enough to reconstruct the
        // stack off-box with addr2line, and they are written with nothing that
        // can block or allocate.  Everything below this point may not run.
        safeWrite(fd, "=== gdb stack unavailable: ");
        safeWrite(fd, gdbFailReason ? gdbFailReason : "unknown");
        safeWrite(fd, " ===\n=== raw frames (subtract the module base from the map below) ===\n");
        for (i = 0; i < frames; i++) {
            safeWriteHex(fd, (uintptr_t)callstack[i]);
            safeWrite(fd, "\n");
        }
        safeWriteModuleMap(fd);

        // Unsafe half: backtrace_symbols() allocates.  Attempted last, and only
        // for readability -- the record above already stands on its own.
        safeWrite(fd, "\n=== symbolized frames (best effort) ===\n");
        char** strs = backtrace_symbols(callstack, frames);
        if (strs) {
            for (i = 0; i < frames; i++) {
                LogErr(VB_ALL, "  %s\n", strs[i]);
            }
            for (i = 0; i < frames; i++) {
                printf("  %s\n", strs[i]);
                write(fd, strs[i], strlen(strs[i]));
                write(fd, "\n", 1);
            }
            free(strs);
        } else {
            safeWrite(fd, "(backtrace_symbols failed)\n");
        }
        write(fd, "\n", 1);
        close(fd);
    }

    // Context files, written unconditionally (the gdb path above produces only
    // a stack).  Separate files so the stack parser is unaffected.
    //
    // Split into two on PRIVACY grounds, and the split must be kept: the
    // playlist state and the fault registers are bare scalars that identify
    // nothing, whereas the log ring is log content and FPP's logs are full of
    // host names, LAN addresses and discovered-device identifiers.  The
    // bundler therefore ships the first at every share level and the second
    // only where logs/fppd.log already goes.  Putting them in one file sends a
    // user's network topology to anyone who selected "stack traces only".
    {
        int cfd = open("/tmp/fppd_crash_context.log", O_WRONLY | O_CREAT | O_TRUNC, S_IRUSR | S_IWUSR);
        if (cfd >= 0) {
            PlaylistDumpCrashState(cfd);
            // Written even when gdb succeeded: gdb reports the registers of
            // the thread it happens to unwind, not necessarily the faulting
            // one, and this costs nothing.
            safeWriteFaultRegisters(cfd, ctx);
            close(cfd);
        }
        int rfd = open("/tmp/fppd_crash_log_ring.log", O_WRONLY | O_CREAT | O_TRUNC, S_IRUSR | S_IWUSR);
        if (rfd >= 0) {
            CrashLogRingDump(rfd);
            close(rfd);
        }
    }
    if (crashLog >= 0) {
        std::set<std::string> filenames;
        std::string mediaDir = getFPPMediaDir();
        std::string cdir = mediaDir + "/crashes";

        chdir(mediaDir.c_str());
        mkdir(cdir.c_str(), S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH);
        SetFilePerms(cdir, true);

        bool hasRecent = false;
        for (const auto& entry : std::filesystem::directory_iterator(cdir)) {
            filenames.insert(entry.path());
            auto ftime = entry.last_write_time();
            std::chrono::system_clock::time_point stm;
#if defined(PLATFORM_OSX)
    #if (__apple_build_version__ >= 14030022)
            stm = std::chrono::time_point_cast<std::chrono::system_clock::duration>(
                std::chrono::file_clock::to_sys(ftime));
    #else
            std::time_t tt = decltype(ftime)::clock::to_time_t(ftime);
            stm = std::chrono::system_clock::from_time_t(tt);
    #endif
#else
            stm = std::chrono::time_point_cast<std::chrono::system_clock::duration>(
                std::chrono::file_clock::to_sys(ftime));
#endif
            auto tdiff = std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now() - stm);
            if (tdiff.count() < 60) {
                hasRecent = true;
            }
        }
        while (filenames.size() > 10) {
            std::string f = *filenames.begin();
            unlink(f.c_str());
            filenames.erase(filenames.begin());
        }

        if (!hasRecent) {
            char tbuffer[32];
            time_t rawtime;
            time(&rawtime);
            struct tm timeinfo;
            localtime_r(&rawtime, &timeinfo);
            strftime(tbuffer, sizeof(tbuffer), "%Y-%m-%d_%H-%M-%S", &timeinfo);
#ifdef PLATFORM_ARMBIAN
            char sysType[] = "Armbian";
#elif defined(PLATFORM_BBB)
            char sysType[] = "BBB";
#elif defined(PLATFORM_BB64)
            char sysType[] = "BB64";
#elif defined(PLATFORM_PI)
            char sysType[] = "Pi";
#elif defined(PLATFORM_OSX)
            char sysType[] = "MacOS";
#elif defined(PLATFORM_DOCKER)
            char sysType[] = "Docker";
#elif defined(PLATFORM_DEBIAN)
            char sysType[] = "Debian";
#else
            char sysType[] = "Unknown";
#endif
            char zfName[256];
            std::string SystemUUID = getSetting("SystemUUID", "unknown");
            char safeUUID[64];
            unsigned int uuidLen = 0;
            for (const char* p = SystemUUID.c_str(); *p != '\0' && uuidLen < sizeof(safeUUID) - 1; ++p) {
                unsigned char c = *p;
                bool safe = (c >= '0' && c <= '9') || (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || c == '-' || c == '_' || c == '.';
                if (safe) {
                    safeUUID[uuidLen++] = c;
                }
            }
            safeUUID[uuidLen] = '\0';
            snprintf(zfName, sizeof(zfName), "crashes/fpp-%s-%s-%s-%s.zip", sysType, getFPPVersion(), safeUUID, tbuffer);

            // Use script to generate crash report with passwords redacted
            char scriptCmd[512];
            snprintf(scriptCmd, sizeof(scriptCmd), "/opt/fpp/scripts/generate_crash_report %d %s", crashLog == 0 ? 3 : crashLog, zfName);
            system(scriptCmd);
            SetFilePerms(zfName);
            
            if (crashLog >= 1) {
                // Upload crash report
                char uploadCmd[512];
                snprintf(uploadCmd, sizeof(uploadCmd), "curl https://dankulp.com/crashUpload/index.php -F userfile=@%s", zfName);
                system(uploadCmd);
            }
        } else {
            LogErr(VB_ALL, "Very recent crash report found, not uploading\n");
        }
    }
    inCrashHandler = false;
    if (s != SIGQUIT && s != SIGUSR1) {
        // For SIGBUS in non-main threads, terminate only the faulting thread
        // instead of the entire process.  This allows fppd to survive
        // DRM/KMS buffer crashes in video consumer threads while keeping
        // audio and other functionality running.
#ifndef PLATFORM_OSX
        if (s == SIGBUS && gettid() != getpid()) {
            LogErr(VB_ALL, "SIGBUS in non-main thread %u — terminating thread only\n", gettid());
#else
        if (s == SIGBUS && !pthread_main_np()) {
            uint64_t tid = 0;
            pthread_threadid_np(NULL, &tid);
            LogErr(VB_ALL, "SIGBUS in non-main thread %llu — terminating thread only\n", tid);
#endif
            WarningHolder::AddWarning(1, "Video thread crashed (SIGBUS). Video output may be unavailable.");
            WarningHolder::WriteWarningsFile();
            // Restore default SIGBUS handler for this thread so the
            // pthread_exit cleanup doesn't loop back here if it touches
            // the same bad mapping.
            struct sigaction sa;
            sa.sa_handler = SIG_DFL;
            sigemptyset(&sa.sa_mask);
            sa.sa_flags = 0;
            sigaction(SIGBUS, &sa, NULL);
            // The process survives this path — disarm the crash watchdog.
            alarm(0);
            pthread_exit(NULL);
            return; // unreachable, but satisfies compiler
        }
        runMainFPPDLoop = 0;
        WarningHolder::StopNotifyThread();
        WarningHolder::RemoveAllWarnings();
        WarningHolder::AddWarning(1, "FPPD has crashed.  Check crash reports.");
        WarningHolder::WriteWarningsFile();
        exit(-1);
    }
}

bool setupExceptionHandlers() {
    // old sig handlers
    static bool s_savedHandlers = false;
    static struct sigaction s_handlerFPE,
        s_handlerILL,
        s_handlerBUS,
        s_handlerSEGV,
        s_handlerABRT;

    bool ok = true;
    if (!s_savedHandlers) {
        // install the signal handler
        struct sigaction act;

        // some systems extend it with non std fields, so zero everything
        memset(&act, 0, sizeof(act));

        act.sa_sigaction = handleCrash;
        sigemptyset(&act.sa_mask);
        act.sa_flags = SA_SIGINFO;

        ok &= sigaction(SIGFPE, &act, &s_handlerFPE) == 0;
        ok &= sigaction(SIGILL, &act, &s_handlerILL) == 0;
        ok &= sigaction(SIGBUS, &act, &s_handlerBUS) == 0;
        ok &= sigaction(SIGSEGV, &act, &s_handlerSEGV) == 0;
        ok &= sigaction(SIGABRT, &act, &s_handlerABRT) == 0;
        ok &= sigaction(SIGQUIT, &act, nullptr) == 0;
        ok &= sigaction(SIGUSR1, &act, nullptr) == 0;

        struct sigaction sigchld_action;
        sigchld_action.sa_handler = SIG_DFL;
        sigchld_action.sa_flags = SA_NOCLDWAIT;
        sigemptyset(&sigchld_action.sa_mask);
        ok &= sigaction(SIGCHLD, &sigchld_action, NULL) == 0;

        if (!ok) {
            LogWarn(VB_ALL, "Failed to install our signal handler.\n");
        }
        s_savedHandlers = true;
    } else if (s_savedHandlers) {
        // uninstall the signal handler
        ok &= sigaction(SIGFPE, &s_handlerFPE, NULL) == 0;
        ok &= sigaction(SIGILL, &s_handlerILL, NULL) == 0;
        ok &= sigaction(SIGBUS, &s_handlerBUS, NULL) == 0;
        ok &= sigaction(SIGSEGV, &s_handlerSEGV, NULL) == 0;
        ok &= sigaction(SIGABRT, &s_handlerABRT, NULL) == 0;
        if (!ok) {
            LogWarn(VB_ALL, "Failed to install default signal handlers.\n");
        }
        s_savedHandlers = false;
    }
    return ok;
}

static void initCapeFromFile(const std::string& f) {
    if (FileExists(f)) {
        Json::Value root;
        if (LoadJsonFromFile(f, root, JsonRoot::Object)) {
            // if there are sources of sensor data, get them loaded first
            if (root.isMember("sensorSources")) {
                Sensors::INSTANCE.addSensorSources(root["sensorSources"]);
            }
            Sensors::INSTANCE.addSensors(root["sensors"]);
        }
    }
}
static void initCape() {
    initCapeFromFile(FPP_DIR_MEDIA("/tmp/cape-sensors.json"));
}

void usage(char* appname) {
    printf("Usage: %s [OPTION...]\n"
           "\n"
           "fppd is the Falcon Player daemon.\n"
           "\n"
           "Options:\n"
           "  -f, --foreground              - Don't daemonize the application.  When run\n"
           "                                  from a terminal, log lines are echoed to the\n"
           "                                  console in addition to the log file.  (Under\n"
           "                                  systemd, where stdout is not a terminal, the\n"
           "                                  console echo is suppressed to avoid doubling\n"
           "                                  every line into the journal.)\n"
           "  -d, --daemonize               - Daemonize even if the config file says not to.\n"
           "  -v, --volume VOLUME           - Set a volume (over-written by config file)\n"
           "  -m, --mode MODE               - Set the mode: \"player\", \"bridge\",\n"
           "                                  \"master\", or \"remote\"\n"
           "  -l, --log-file FILENAME       - Set the log file.  Use \"stdout\" or \"stderr\"\n"
           "                                  to log to the console instead of a file.\n"
           "  -H  --detect-hardware         - Detect Falcon hardware on SPI port\n"
           "  -C  --configure-hardware      - Configure detected Falcon hardware on SPI\n"
           "  -h, --help                    - This menu.\n"
           "      --log-level LEVEL         - Set the global log output level (all loggers):\n"
           "                                  \"info\", \"warn\", \"debug\", \"excess\")\n"
           "      --log-level LEVEL:logger  - Set the log level for one or more loggers.\n"
           "                                  each level should be separated by semicolons\n"
           "                                  with one or more loggers separated by commas.\n"
           "                                  example: debug:schedule,player;excess:mqtt \n"
           "                                  valid loggers are: \n"
           "                                    ChannelData - channel data itself\n"
           "                                    ChannelOut  - channel output code\n"
           "                                    Command     - command processing\n"
           "                                    Control     - Control socket debugging\n"
           "                                    E131Bridge  - E1.31 bridge\n"
           "                                    Effect      - Effects sequences\n"
           "                                    General     - general messages\n"
           "                                    GPIO        - GPIO Input handling\n"
           "                                    HTTP        - HTTP API requests\n"
           "                                    MediaOut    - Media file handling\n"
           "                                    Playlist    - Playlist handling\n"
           "                                    Plugin      - Plugin handling\n"
           "                                    Schedule    - Playlist scheduling\n"
           "                                    Sequence    - Sequence parsing\n"
           "                                    Setting     - Settings parsing\n"
           "                                    Sync        - Player/Remote Synchronization\n"
           "                                  The default logging is read from settings\n",
           appname);
}

int parseArguments(int argc, char** argv) {
    char* s = NULL;
    int c;

    SetSetting("logFile", FPP_FILE_LOG);

    while (1) {
        int this_option_optind = optind ? optind : 1;
        int option_index = 0;
        static struct option long_options[] = {
            { "displayvers", no_argument, 0, 'V' },
            { "foreground", no_argument, 0, 'f' },
            { "daemonize", no_argument, 0, 'd' },
            { "restarted", no_argument, 0, 'r' },
            { "volume", required_argument, 0, 'v' },
            { "mode", required_argument, 0, 'm' },
            { "log-file", required_argument, 0, 'l' },
            { "playlist", required_argument, 0, 'p' },
            { "position", required_argument, 0, 'P' },
            { "detect-piface", no_argument, 0, 4 },
            { "resume-unscheduled", required_argument, 0, 5 },
            { "help", no_argument, 0, 'h' },
            { "log-level", required_argument, 0, 2 },
            { 0, 0, 0, 0 }
        };

        c = getopt_long(argc, argv, "Vfdrv:m:l:p:P:h",
                        long_options, &option_index);
        if (c == -1)
            break;

        switch (c) {
        case 'V':
            printVersionInfo();
            exit(0);
        case 2: // log-level
            if (SetLogLevelComplex(optarg)) {
                std::cout << FPPLogger::INSTANCE.GetLogLevelString() << std::endl;
                LogInfo(VB_SETTING, "Log Level set to %d (%s)\n", FPPLogger::INSTANCE.MinimumLogLevel(), optarg);
            }
            break;
        case 'f': // foreground
            SetSetting("daemonize", 0);
            break;
        case 'd': // daemonize
            SetSetting("daemonize", 1);
            break;
        case 'r': // restarted
            SetSetting("restarted", 1);
            break;
        case 'p': // playlist
            SetSetting("resumePlaylist", optarg);
            break;
        case 'P': // position
            SetSetting("resumePosition", atoi(optarg));
            break;
        case 5: // resume-unscheduled <repeat>
            // -p/-P alone only restore the POSITION of a playlist the scheduler
            // is about to start anyway (Scheduler::PlayScheduledItem).  This
            // says "start it yourself if the scheduler doesn't", which is what
            // a self-initiated recovery restart of a manually-started show
            // needs (issue #2727).  The argument carries the repeat mode.
            SetSetting("resumeUnscheduled", 1);
            SetSetting("resumeRepeat", atoi(optarg));
            break;
        case 'v': // volume
            setVolume(atoi(optarg));
            break;
        case 'm': // mode
            SetSetting("fppMode", optarg);
            break;
        case 'l': // log-file
            SetSetting("logFile", optarg);
            break;
        case 'h': // help
            usage(argv[0]);
            exit(EXIT_SUCCESS);
            break;
        default:
            usage(argv[0]);
            exit(EXIT_FAILURE);
        }
    }

    // fppd is the one binary that asks for the stdout copy to be dropped once a
    // line is in the log file: "-f" is how systemd runs it, so !daemonize is true
    // in normal operation and every line would otherwise be duplicated into
    // journald. (An interactive `fppd -f` still echoes -- log.cpp checks isatty.)
    // The suppression is opt-in precisely so fppoled and the other small services
    // that link this logger keep showing up in `journalctl -u <service>`.
    SetSuppressDuplicateStdOut(true);
    SetLogFile(getSetting("logFile").c_str(), !getSettingInt("daemonize"));

    return 0;
}

// Workaround ASan bug 27790 (https://bugs.llvm.org//show_bug.cgi?id=27790)
// by logging if LD_LIBRARY_PATH doesn't include the path to argv[0] (our binary).
// This is because ASan intercepts dlopen and causes calls to dlopen to use ASan's
// rpath instead of the rpath of the calling DSO. We cannot change the
// LD_LIBRARY_PATH env var because the loader has already processed it by the time
// that main() is called. We could fork()/execvpe(), but this has implications for
// things like debugging that may be monitoring our pid.
bool checkASan(int argc, char** argv) {
#if __SANITIZE_ADDRESS__
    {
        struct FreeString {
            void operator()(char* p) {
                free(p);
            }
        };
        if (argc < 1 || !argv[0])
            abort(); // shouldn't happen
        std::unique_ptr<char[], FreeString> self(realpath(argv[0], NULL));
        if (!self)
            abort(); // shouldn't happen
        size_t sep = std::string_view(self.get()).rfind('/');
        if (sep == std::string_view::npos)
            abort(); // shouldn't happen
        self[sep] = '\0';

        auto libraryPath = getenv("LD_LIBRARY_PATH");
        std::string_view libraryPathSv(libraryPath ? libraryPath : "");
        bool found = false;
        for (size_t start = 0, index = libraryPathSv.find(':');; start = index + 1, index = libraryPathSv.find(':', index + 1)) {
            if (auto pathSV = libraryPathSv.substr(start, index - start); !pathSV.empty()) {
                std::unique_ptr<char[], FreeString> resolved(realpath(std::string(pathSV).c_str(), NULL));
                if (resolved && strcmp(self.get(), resolved.get()) == 0) {
                    found = true;
                    break;
                }
            }
            if (index == libraryPathSv.npos)
                break;
        }

        if (!found) {
            constexpr static char str[] = "When built with ASan, LD_LIBRARY_PATH must be set to include the path to fppd. Exiting.\n";
            LogErr(VB_GENERAL, str);
            fprintf(stderr, str);
            return false;
        }
    }
#endif

    return true;
}

int main(int argc, char* argv[]) {
    auto ensureEnvDefault = [](const char* key, const char* value) {
        if (!getenv(key)) {
            setenv(key, value, 0);
        }
    };

    // Force line-buffered stdout so logs via systemd/journald appear promptly
    setvbuf(stdout, NULL, _IOLBF, 0);

    setupExceptionHandlers();
    FPPLogger::INSTANCE.Init();

    if (!checkASan(argc, argv))
        return 1;

    LoadSettings(argv[0]);

    // Align runtime audio library backend defaults with configured FPP backend.
    // This is a safety net in case the service env file is stale/missing.
    std::string mediaBackend = toLowerCopy(getSetting("MediaBackend"));
    if (mediaBackend == "pipewire" || mediaBackend == "pipewire-simple") {
        ensureEnvDefault("SDL_AUDIODRIVER", "pulse");
        ensureEnvDefault("ALSOFT_DRIVERS", "pulse");
    } else {
        ensureEnvDefault("SDL_AUDIODRIVER", "alsa");
        ensureEnvDefault("ALSOFT_DRIVERS", "alsa");
    }
    LogInfo(VB_MEDIAOUT, "Audio env: SDL_AUDIODRIVER=%s  ALSOFT_DRIVERS=%s\n",
            getenv("SDL_AUDIODRIVER") ? getenv("SDL_AUDIODRIVER") : "(unset)",
            getenv("ALSOFT_DRIVERS") ? getenv("ALSOFT_DRIVERS") : "(unset)");

    curl_global_init(CURL_GLOBAL_ALL);

    // Initialize Magick, but we don't want the Magick signal handlers as they interfere with our own
    MagickLib::InitializeMagickEx(nullptr, MAGICK_OPT_NO_SIGNAL_HANDER, nullptr);
    Magick::InitializeMagick(NULL);

    // Parse our arguments first, override any defaults
    parseArguments(argc, argv);

    // Check to see if we were restarted and should skip sending blanking data at startup
    if (FileExists(FPP_DIR_MEDIA("/tmp/fppd_restarted"))) {
        unlink(FPP_DIR_MEDIA("/tmp/fppd_restarted").c_str());
        setSetting("restarted", 1);
    }
    std::string restartFlag = getSetting("restartFlag", "0");
    if (restartFlag == "2") {
        // if this was a restart and a "quick" was requested, then mark as restarted
        setSetting("restartFlag", "0", true);
    }
    if (loggingToFile()) {
        logVersionInfo();
    }

    FileMonitor::INSTANCE.AddFile(
        "FPPD:Settings", FPP_DIR_MEDIA("/settings"), [argv]() {
        LogDebug(VB_SETTING, "Settings file changed, reloading settings\n");
        LoadSettings(argv[0], true); }, true);

    // Start functioning
    if (getSettingInt("daemonize")) {
        CreateDaemon();
    }
    PLAT_GPIO_CLASS* gpioUtil = new PLAT_GPIO_CLASS();
    PinCapabilities::InitGPIO("FPPD", gpioUtil);

    // No srand() needed: FPPrand() seeds a per-thread PRNG on first use.

    CommandManager::INSTANCE.Init();
    if (getSetting("MQTTHost") != "") {
        LogInfo(VB_GENERAL, "Creating MQTT\n");
        mqtt = new MosquittoClient(getSetting("MQTTHost").c_str(), getSettingInt("MQTTPort"), getSetting("MQTTPrefix").c_str());

        if (!mqtt || !mqtt->Init(getSetting("MQTTUsername").c_str(), getSetting("MQTTPassword").c_str(), getSetting("MQTTCaFile").c_str())) {
            LogWarn(VB_CONTROL, "MQTT Init failed. Starting without MQTT. -- Maybe MQTT host doesn't resolve\n");
            WarningHolder::AddWarning(4, "MQTT init failed at startup - check the MQTT host/port settings");
        } else {
            Events::AddEventHandler(mqtt);
        }
    }

    std::function<void(const std::string&, const std::string&)>
        fppd_callback = [](const std::string& topic_in,
                           const std::string& payload) {
            LogDebug(VB_CONTROL, "System Callback for %s\n", topic_in.c_str());

            if (0 == topic_in.compare(topic_in.length() - 5, 5, "/stop")) {
                LogInfo(VB_CONTROL, "Stopping FPP for request:   %s\n", topic_in.c_str());
                ShutdownFPPD(false);
            } else if (0 == topic_in.compare(topic_in.length() - 8, 8, "/restart")) {
                LogInfo(VB_CONTROL, "Restarting FPP for request:   %s\n", topic_in.c_str());
                ShutdownFPPD(true);
            } else {
                LogWarn(VB_CONTROL, "Invalid request in fppd_callback  %s\n", topic_in.c_str());
            }
        };
    std::function<void(const std::string&, const std::string&)>
        system_callback = [](const std::string& topic_in,
                             const std::string& payload) {
            LogDebug(VB_CONTROL, "System Callback for %s\n", topic_in.c_str());
            std::string rc = "";

            if (0 == topic_in.compare(topic_in.length() - 9, 9, "/shutdown")) {
                LogInfo(VB_CONTROL, "Shutting down OS for request:   %s\n", topic_in.c_str());
                urlGet("http://localhost/api/system/shutdown", rc);
            } else if (0 == topic_in.compare(topic_in.length() - 8, 8, "/restart")) {
                LogInfo(VB_CONTROL, "Restarting FPP for request:   %s\n", topic_in.c_str());
                urlGet("http://localhost/api/system/reboot", rc);
            } else {
                LogWarn(VB_CONTROL, "Invalid  request in mqtt_system_callback  %s\n", topic_in.c_str());
            }
        };

    Events::AddCallback("/system/fppd/#", fppd_callback);
    Events::AddCallback("/system/shutdown", system_callback);
    Events::AddCallback("/system/restart", system_callback);

    WarningHolder::StartNotifyThread();

    // Check if boot delay is in progress and add warning
    if (FileExists(getFPPMediaDir("/tmp/boot_delay"))) {
        std::string delayInfo = GetFileContents(getFPPMediaDir("/tmp/boot_delay"));
        TrimWhiteSpace(delayInfo);
        std::string msg;

        // Parse the delay info - format is "startTime,duration" or "startTime,auto"
        size_t commaPos = delayInfo.find(',');
        if (commaPos != std::string::npos && commaPos + 1 < delayInfo.length()) {
            std::string delayValue = delayInfo.substr(commaPos + 1);
            if (delayValue == "auto") {
                msg = "Boot delay in progress: Waiting for valid system time (NTP/RTC) - up to 5 minutes";
            } else {
                msg = "Boot delay in progress: Waiting " + delayValue + " seconds before starting FPPD";
            }
        } else {
            // Fallback for old format or malformed data
            if (delayInfo == "auto") {
                msg = "Boot delay in progress: Waiting for valid system time (NTP/RTC) - up to 5 minutes";
            } else {
                msg = "Boot delay in progress: Waiting " + delayInfo + " seconds before starting FPPD";
            }
        }
        WarningHolder::AddWarning(12, msg);
    }

    LogInfo(VB_GENERAL, "Creating Scheduler, Playlist, and Sequence\n");
    scheduler = new Scheduler();
    sequence = new Sequence();
    LogInfo(VB_GENERAL, "Creation of Scheduler, Playlist, and Sequence Complete\n");

    if (!MultiSync::INSTANCE.Init()) {
        exit(EXIT_FAILURE);
    }

    Sensors::INSTANCE.DetectHWSensors();
    initCape();

    if (FileExists(FPP_DIR_CONFIG("/sensors.json"))) {
        Json::Value root;
        if (LoadJsonFromFile(FPP_DIR_CONFIG("/sensors.json"), root, JsonRoot::Object)) {
            Sensors::INSTANCE.addSensors(root["sensors"]);
        }
    }

    Player::INSTANCE.Init();
    PluginManager::INSTANCE.init();

    InitMediaOutput();
#ifdef HAS_AES67_GSTREAMER
    AES67Manager::INSTANCE.Init();
    AES67Manager::INSTANCE.ApplyConfig();
#endif
#ifdef HAS_OPUS_RTP_GSTREAMER
    OpusRTPManager::INSTANCE.Init();
    OpusRTPManager::INSTANCE.ApplyConfig();
#endif
    VideoInputManager::Instance().Init();
    VideoOutputManager::Instance().Init();
    PixelOverlayManager::INSTANCE.Initialize();
    PingManager::INSTANCE.Initialize();
    WLEDAPIResponder::INSTANCE.Initialize();
    WLEDAudioSync::INSTANCE.Initialize();
    InitializeChannelOutputs();
    PluginManager::INSTANCE.loadUserPlugins();

    InitEffects();
    ChannelTester::INSTANCE.RegisterCommands();
    LocaleHolder::RegisterCommands();

    multiSync->WriteRuntimeInfoFile();

    MainLoop();
    // DISABLED: Stats collected while fppd is shutting down
    // incomplete and cause problems with summary
    // PublishStatsForce("Shutdown"); // not background

    if (CommandManager::INSTANCE.HasPreset("FPPD_STOPPED")) {
        CommandManager::INSTANCE.TriggerPreset("FPPD_STOPPED");
    }

    // turn off processing of events so we don't get
    // events while we are shutting down
    Events::PrepareForShutdown();

    // Tear down mDNS *first* so the goodbye packets for our advertised
    // services go out on the wire before anything slower (media output
    // shutdown, channel-output close, or the WS responder draining its
    // client list) has a chance to hang. If shutdown is force-killed
    // partway through (e.g. fppd_stop's 1s timeout), at least other
    // discovery clients won't keep our entries cached for the TTL.
    MDNSManager::INSTANCE.Cleanup();

    VideoInputManager::Instance().Shutdown();
    VideoOutputManager::Instance().Shutdown();
#ifdef HAS_AES67_GSTREAMER
    AES67Manager::INSTANCE.Shutdown();
#endif
#ifdef HAS_OPUS_RTP_GSTREAMER
    OpusRTPManager::INSTANCE.Shutdown();
#endif
    CleanupMediaOutput();
    CloseEffects();
    CloseChannelOutputs();
    WLEDAPIResponder::INSTANCE.Cleanup();
    WLEDAudioSync::INSTANCE.Cleanup();
    PingManager::INSTANCE.Cleanup();
    OutputMonitor::INSTANCE.Cleanup();
    // Plugins must clean up before CommandManager: their unregister hooks
    // pull the commands they own out of the registry so CommandManager's
    // bulk delete below doesn't free objects a plugin still references.
    PluginManager::INSTANCE.Cleanup();
    CommandManager::INSTANCE.Cleanup();
    MultiSync::INSTANCE.ShutdownSync();
    GPIOManager::INSTANCE.Cleanup();

    // Stop the notify thread before the deletes below, not after: its listeners
    // run arbitrary code on a warning change or notify timeout, and the status
    // listeners among them build a full status payload from scheduler and
    // sequence. Leaving it running across the deletes gives every shutdown a
    // window where a warning change reads freed objects.
    WarningHolder::StopNotifyThread();

    delete scheduler;
    delete sequence;
    runMainFPPDLoop = -1;
    Sensors::INSTANCE.Close();
    RecurringTasks::INSTANCE.Close();
    Variables::INSTANCE.Close();

    if (mqtt) {
        Events::RemoveEventHandler(mqtt);
        delete mqtt;
    }
    delete gpioUtil;

    MagickLib::DestroyMagick();
    curl_global_cleanup();
    std::string logLevelString = FPPLogger::INSTANCE.GetLogLevelString();

    // Decide the restart resume HERE, while the log file is still open:
    // everything logged after CloseOpenFiles() below is silently discarded
    // (which is why "Performing Restart." has never appeared in a support log),
    // and "my show never came back after a restart" is otherwise
    // indistinguishable from "no playlist was running" (issue #2727).
    //
    // A manually-started playlist is normally NOT resumed across a restart -- a
    // user-requested restart shouldn't silently re-start a show they stopped by
    // restarting.  A recovery restart we initiated ourselves is the opposite
    // case: the playlist was running, nobody asked for it to stop, and coming
    // back idle strands every synced remote mid-clip on a frozen frame.
    std::string resumePlaylist;
    std::string resumePosition;
    std::string resumeRepeat;
    bool resumeUnscheduled = false;
    if (restartFPPD) {
        if ((Player::INSTANCE.GetStatus() == FPP_STATUS_PLAYLIST_PLAYING) &&
            (Player::INSTANCE.WasScheduled() || RestartShouldResumePlaylist())) {
            resumePlaylist = Player::INSTANCE.GetPlaylistName();
            resumePosition = std::to_string(Player::INSTANCE.GetPosition() - 1);
            resumeRepeat = std::to_string(Player::INSTANCE.GetRepeat());
            // Force-start only what the scheduler won't restore itself.  A
            // scheduled playlist is left to CheckIfShouldBePlayingNow(), which
            // is schedule-window aware -- forcing that one would restart a show
            // whose window closed while we were restarting.
            resumeUnscheduled = RestartShouldResumePlaylist() && !Player::INSTANCE.WasScheduled();
            LogInfo(VB_GENERAL, "Restart: resuming playlist '%s' at position %s (repeat %s, unscheduled resume %d)\n",
                    resumePlaylist.c_str(), resumePosition.c_str(), resumeRepeat.c_str(),
                    resumeUnscheduled ? 1 : 0);
        } else {
            LogInfo(VB_GENERAL, "Restart: not resuming a playlist (status %d, scheduled %d, resume requested %d)\n",
                    (int)Player::INSTANCE.GetStatus(), Player::INSTANCE.WasScheduled(),
                    RestartShouldResumePlaylist() ? 1 : 0);
        }
    }

    CloseCommand();
    CloseOpenFiles(getSettingInt("daemonize"));

    WarningHolder::ClearWarningsFile();

    if (restartFPPD) {
        remove(FPP_DIR_MEDIA("/fpp-info.json").c_str());

        std::string fppdDir = getFPPDDir("/src/fppd");
        const char* dmode = getSettingInt("daemonize") ? "-d" : "-f";
        if (!resumePlaylist.empty()) {
            if (resumeUnscheduled) {
                // We asked for this restart, so the show must come back even
                // when no schedule would start it (issue #2727).  -p/-P alone
                // only restore the position of a playlist the scheduler is
                // already starting.
                execlp(fppdDir.c_str(), fppdDir.c_str(), dmode, "--log-level", logLevelString.c_str(), "-r", "-p", resumePlaylist.c_str(), "-P", resumePosition.c_str(), "--resume-unscheduled", resumeRepeat.c_str(), NULL);
            }
            execlp(fppdDir.c_str(), fppdDir.c_str(), dmode, "--log-level", logLevelString.c_str(), "-r", "-p", resumePlaylist.c_str(), "-P", resumePosition.c_str(), NULL);
        } else {
            execlp(fppdDir.c_str(), fppdDir.c_str(), dmode, "--log-level", logLevelString.c_str(), "-r", NULL);
        }
    }

    // Every subsystem was torn down explicitly above, so the C++ global/static
    // singleton destructors that would run on a normal return are redundant --
    // and crash-prone. Two distinct failure modes show up in the crash reports:
    //   * macOS: a noexcept destructor locks a mutex belonging to an
    //     already-destroyed singleton (or one a still-draining drogon thread is
    //     touching); libc++ throws EINVAL ("mutex lock failed: Invalid
    //     argument") from that lock, which escapes the noexcept dtor and calls
    //     std::terminate.
    //   * Linux: a file-static std::thread (the Events publish thread, the
    //     WarningHolder notify thread, ...) that is still joinable when
    //     __cxa_finalize destroys it -> std::thread::~thread calls
    //     std::terminate. The orderly shutdown above joins these, but a late
    //     restart (e.g. an event reconfigure during the drawn-out shutdown) can
    //     leave one joinable again. This is the single most common fppd crash
    //     on the dashboard, so the same _exit() shortcut macOS uses is applied
    //     on Linux too.
    // Flush and exit now, skipping the redundant (and crash-prone) teardown.
    fflush(nullptr);
    _exit(0);
    return 0;
}

void ShutdownFPPDCallback(bool restart) {
    LogInfo(VB_GENERAL, "Shutting down main loop.\n");

    restartFPPD = restart;
    runMainFPPDLoop = 0;
}

// ──────────────────────────────────────────────────────────────────────────────
// Main-loop stall watchdog (issue #2727).
//
// The main loop services the MultiSync control socket, the `fpp` command socket
// and (in remote mode) media processing.  The HTTP API answers on its own
// threads, so when something blocks the main loop the box looks alive from the
// outside while doing nothing: the UI keeps reporting the last status it saw
// ("playing" forever), the received-sync-packet counters stop moving because
// ProcessControlPacket() never runs again, and "Restart FPPD" is a no-op
// because that command is delivered through the same unserviced command
// socket.  That combination is exactly what a wedged remote looks like, and
// nothing short of a power cycle recovers it.
//
// So heartbeat the loop and supervise it from a thread it cannot block: once
// the loop goes quiet, dump a backtrace of every thread (the diagnostic that
// has been missing from every report of this), tell the UI that the status it
// is showing is stale, and if the loop never comes back, exit so systemd
// (Restart=always) starts a clean process.  Exiting rather than re-exec'ing is
// deliberate: a stalled loop normally means a wedged decoder/DRM fd, and open
// fds without CLOEXEC survive exec — only a fresh process gets them back from
// the kernel.
//
// The show is restarted through the same resume path a wedge restart uses.
// The snapshot lives in tmpfs so it can never resurrect a playlist after a
// reboot, and it is taken by the main loop (never read out of Player from the
// watchdog thread, which would race with whatever the stalled thread is doing).
// ──────────────────────────────────────────────────────────────────────────────
static constexpr const char* STALL_RESUME_STATE_FILE = "/run/fppd/stall_resume";
static std::atomic<long long> s_mainLoopHeartbeat{ 0 };
static std::atomic<bool> s_mainLoopWatchdogRunning{ false };

// Which call the main loop last entered (SetMainLoopPhase, in common.cpp, so
// code inside libfpp can narrow it further).  Only ever set to string literals,
// so the watchdog can read the pointer from another thread and print it even
// while the loop is wedged inside that call.  A stalled loop that gdb cannot
// unwind (the 2026-07-27 FPPv4-4 capture: the main thread's backtrace stopped
// at a single bare libc frame) still tells us which call it is in.
#define MAIN_LOOP_PHASE(p) SetMainLoopPhase(p)

static std::mutex s_mainLoopShowLock;
static std::string s_mainLoopShowPlaylist;
static int s_mainLoopShowPosition = 0;
static int s_mainLoopShowRepeat = 0;
static bool s_mainLoopShowScheduled = false;

static long long MonotonicMS() {
    // Deliberately not GetTimeMS(): that is wall clock, and an NTP step would
    // read as a multi-second "stall".
    return std::chrono::duration_cast<std::chrono::milliseconds>(
               std::chrono::steady_clock::now().time_since_epoch())
        .count();
}

// Called from the main loop only.
static void RecordMainLoopShowSnapshot() {
    std::unique_lock<std::mutex> lock(s_mainLoopShowLock, std::try_to_lock);
    if (!lock.owns_lock()) {
        return;
    }
    if (Player::INSTANCE.GetStatus() == FPP_STATUS_PLAYLIST_PLAYING) {
        s_mainLoopShowPlaylist = Player::INSTANCE.GetPlaylistName();
        s_mainLoopShowPosition = Player::INSTANCE.GetPosition() - 1;
        s_mainLoopShowRepeat = Player::INSTANCE.GetRepeat();
        s_mainLoopShowScheduled = Player::INSTANCE.WasScheduled();
    } else if (!s_mainLoopShowPlaylist.empty()) {
        s_mainLoopShowPlaylist.clear();
    }
}

// Last act before the watchdog exits the process: leave behind whatever the
// show was doing so the fresh process picks it back up.
static void WriteStallResumeState() {
    std::unique_lock<std::mutex> lock(s_mainLoopShowLock, std::try_to_lock);
    if (!lock.owns_lock() || s_mainLoopShowPlaylist.empty()) {
        return;
    }
    std::ofstream out(STALL_RESUME_STATE_FILE, std::ios::trunc);
    if (!out) {
        return; // no /run/fppd (macOS, docker) -- nothing to resume from
    }
    out << s_mainLoopShowPlaylist << "\n"
        << s_mainLoopShowPosition << "\n"
        << s_mainLoopShowRepeat << "\n"
        << (s_mainLoopShowScheduled ? 1 : 0) << "\n";
}

// Startup counterpart: turn a stall-restart snapshot into the same settings a
// self-restart would have passed on the command line, then consume the file.
static void ApplyStallResumeState() {
    if (!FileExists(STALL_RESUME_STATE_FILE)) {
        return;
    }
    std::string playlist;
    int position = 0, repeat = 0, scheduled = 0;
    {
        std::ifstream in(STALL_RESUME_STATE_FILE);
        std::string line;
        if (std::getline(in, playlist) && std::getline(in, line)) {
            position = atoi(line.c_str());
            if (std::getline(in, line)) {
                repeat = atoi(line.c_str());
            }
            if (std::getline(in, line)) {
                scheduled = atoi(line.c_str());
            }
        }
    }
    (void)remove(STALL_RESUME_STATE_FILE);
    if (playlist.empty()) {
        return;
    }
    LogWarn(VB_GENERAL, "Previous fppd was killed by the main-loop watchdog while playing '%s' — resuming at position %d\n",
            playlist.c_str(), position);
    SetSetting("resumePlaylist", playlist);
    SetSetting("resumePosition", position);
    if (!scheduled) {
        // Same rule as a wedge restart: the scheduler restores a scheduled
        // playlist itself (and is window-aware about it); an unscheduled show
        // has to be force-started or every synced remote is stranded.
        SetSetting("resumeUnscheduled", 1);
        SetSetting("resumeRepeat", repeat);
    }
}

#ifndef PLATFORM_OSX
// Read a small /proc file into a stack buffer.  Everything in this dump is
// deliberately heap-free: the whole point of running it is that some thread is
// stuck, and if what it is stuck on is the malloc arena lock then anything that
// allocates would wedge the watchdog too.
static ssize_t ReadProcFile(const char* path, char* buf, size_t bufLen) {
    int fd = open(path, O_RDONLY | O_CLOEXEC);
    if (fd < 0) {
        return -1;
    }
    ssize_t len = read(fd, buf, bufLen - 1);
    close(fd);
    if (len < 0) {
        len = 0;
    }
    buf[len] = 0;
    while (len > 0 && (buf[len - 1] == '\n' || buf[len - 1] == ' ')) {
        buf[--len] = 0;
    }
    return len;
}

// Turn a runtime address into "libfoo.so+0x1234" so a PC captured on someone
// else's Pi can be resolved offline against the matching binary.  gdb prints
// the raw address only, which is useless once the process is gone.
static void ResolveAddr(unsigned long addr, char* out, size_t outLen) {
    snprintf(out, outLen, "0x%lx", addr);
    int fd = open("/proc/self/maps", O_RDONLY | O_CLOEXEC);
    if (fd < 0) {
        return;
    }
    char buf[4096];
    char line[512];
    size_t lineLen = 0;
    ssize_t got;
    while ((got = read(fd, buf, sizeof(buf))) > 0) {
        for (ssize_t i = 0; i < got; i++) {
            if (buf[i] != '\n') {
                if (lineLen < sizeof(line) - 1) {
                    line[lineLen++] = buf[i];
                }
                continue;
            }
            line[lineLen] = 0;
            lineLen = 0;

            unsigned long start = 0, end = 0, fileOff = 0;
            char perms[8], path[256];
            path[0] = 0;
            if (sscanf(line, "%lx-%lx %7s %lx %*s %*u %255s",
                       &start, &end, perms, &fileOff, path) >= 4 &&
                addr >= start && addr < end && path[0] == '/') {
                const char* base = strrchr(path, '/');
                snprintf(out, outLen, "%s+0x%lx", base ? base + 1 : path,
                         addr - start + fileOff);
                close(fd);
                return;
            }
        }
    }
    close(fd);
}

// One line per thread naming the syscall it is parked in, the kernel wait
// channel, and the resolved user-space PC.  This is the diagnostic gdb could
// not give us: on 32-bit ARM the unwinder gives up inside libc's lock/futex
// stubs, so the one thread that matters -- the stalled one -- comes back as a
// single unnamed frame.  /proc always answers.
static void DumpThreadStates(void) {
    struct LinuxDirent64 {
        uint64_t d_ino;
        int64_t d_off;
        unsigned short d_reclen;
        unsigned char d_type;
        char d_name[];
    };

    int fd = open("/proc/self/task", O_RDONLY | O_DIRECTORY | O_CLOEXEC);
    if (fd < 0) {
        return;
    }
    // glibc futexes on the mutex word itself, which for a std::mutex is offset
    // 0 -- so a "syscall=98(<addr>,...)" line below whose first argument is one
    // of these is naming the exact lock the thread is stuck on.  Anything else
    // means the contended lock is internal to GStreamer/PipeWire/libc.
    LogErr(VB_GENERAL, "Main loop watchdog: known locks: mediaOutputLock=%p\n",
           (void*)&mediaOutputLock);
    LogErr(VB_GENERAL, "Main loop watchdog: thread states (tid name state wchan syscall pc):\n");

    char dirBuf[8192];
    long n;
    while ((n = syscall(SYS_getdents64, fd, dirBuf, sizeof(dirBuf))) > 0) {
        for (long off = 0; off < n;) {
            LinuxDirent64* d = (LinuxDirent64*)(dirBuf + off);
            off += d->d_reclen;
            if (d->d_name[0] < '0' || d->d_name[0] > '9') {
                continue;
            }

            char path[128], comm[64] = "?", wchan[64] = "?", sc[256] = "?", stat[512];
            snprintf(path, sizeof(path), "/proc/self/task/%s/comm", d->d_name);
            ReadProcFile(path, comm, sizeof(comm));
            snprintf(path, sizeof(path), "/proc/self/task/%s/wchan", d->d_name);
            ReadProcFile(path, wchan, sizeof(wchan));
            snprintf(path, sizeof(path), "/proc/self/task/%s/syscall", d->d_name);
            ReadProcFile(path, sc, sizeof(sc));

            // /proc/<tid>/stat: the state letter is the field after the
            // parenthesised comm, which can itself contain spaces/parens.
            char state = '?';
            snprintf(path, sizeof(path), "/proc/self/task/%s/stat", d->d_name);
            if (ReadProcFile(path, stat, sizeof(stat)) > 0) {
                const char* p = strrchr(stat, ')');
                if (p && p[1] && p[2]) {
                    state = p[2];
                }
            }

            // "<nr> <arg0..arg5> <sp> <pc>", or "running", or "-1 <sp> <pc>".
            long nr = -1;
            unsigned long args[6] = { 0 }, sp = 0, pc = 0;
            int fields = sscanf(sc, "%ld 0x%lx 0x%lx 0x%lx 0x%lx 0x%lx 0x%lx 0x%lx 0x%lx",
                                &nr, &args[0], &args[1], &args[2], &args[3], &args[4],
                                &args[5], &sp, &pc);
            char pcStr[128] = "-";
            if (fields == 9) {
                ResolveAddr(pc, pcStr, sizeof(pcStr));
                // arg0 of a futex wait is the lock address -- the only way to
                // tell "two threads fighting over one mutex" from "two threads
                // idle on their own condvars".
                LogErr(VB_GENERAL, "  tid %-6s %-16s %c %-24s syscall=%ld(0x%lx,0x%lx,0x%lx) pc=%s\n",
                       d->d_name, comm, state, wchan, nr, args[0], args[1], args[2], pcStr);
            } else {
                LogErr(VB_GENERAL, "  tid %-6s %-16s %c %-24s syscall=%s\n",
                       d->d_name, comm, state, wchan, sc);
            }
        }
    }
    close(fd);
}
#else
static void DumpThreadStates(void) {}
#endif

// Kill the process now, leaving the show behind for the next one.  Used for
// both a stalled loop and a stalled shutdown.
static void WatchdogExit(const char* why, long long stalledMS) {
    // Everything below can block if the stalled thread happens to hold a
    // libc/log lock, so make sure the process dies either way first (both
    // calls are async-signal-safe; the crash handler uses the same trick).
    struct sigaction almAct;
    memset(&almAct, 0, sizeof(almAct));
    almAct.sa_handler = SIG_DFL;
    sigemptyset(&almAct.sa_mask);
    sigaction(SIGALRM, &almAct, nullptr);
    alarm(20);

    LogErr(VB_GENERAL, "Main loop watchdog: %s for %lld seconds in '%s' — exiting so a clean fppd is started\n",
           why, stalledMS / 1000, GetMainLoopPhase());
    WriteStallResumeState();
    WarningHolder::WriteWarningsFile();
    fflush(nullptr);
    _Exit(1);
}

// The three timeouts, re-read on every pass.  Reading them once at startup
// meant a change made while fppd was running was silently ignored -- which is
// exactly how these get set, since they are hand-edited hidden settings with no
// UI (2026-07-27: MainLoopStallRestartTimeout="0" was set to keep a stalled
// remote alive for inspection, and the box restarted itself anyway).  Note a
// hand edit of /home/fpp/media/settings still needs something to reload the
// file into fppd; setting it through the UI/API applies immediately.
static void ReadWatchdogTimeouts(int& warnSec, int& restartSec, int& shutdownSec) {
    warnSec = getSettingInt("MainLoopStallTimeout", 30);
    restartSec = getSettingInt("MainLoopStallRestartTimeout", 180);
    shutdownSec = getSettingInt("ShutdownStallTimeout", 120);
    if (restartSec > 0 && restartSec < warnSec) {
        restartSec = warnSec;
    }
}

static void MainLoopWatchdog(int warnSec, int restartSec, int shutdownSec) {
    SetThreadName("FPP-LoopWatchdog");
    bool warned = false;
    long long shutdownStarted = 0;
    while (s_mainLoopWatchdogRunning) {
        std::this_thread::sleep_for(std::chrono::seconds(2));
        if (!s_mainLoopWatchdogRunning) {
            break;
        }
        int prevRestartSec = restartSec;
        ReadWatchdogTimeouts(warnSec, restartSec, shutdownSec);
        if (restartSec != prevRestartSec) {
            LogInfo(VB_GENERAL, "Main loop watchdog: restart timeout changed to %d seconds%s\n",
                    restartSec, restartSec > 0 ? "" : " (restart disabled)");
        }
        if (warnSec <= 0) {
            continue; // disabled at runtime
        }
        if (!runMainFPPDLoop) {
            // Teardown is underway.  It ends in _exit()/execlp(), so this
            // thread simply stops existing on a healthy shutdown; if it is
            // still here much later, the shutdown itself wedged and systemd
            // will never see the process go away.
            if (shutdownSec <= 0) {
                break;
            }
            long long nowMS = MonotonicMS();
            if (!shutdownStarted) {
                shutdownStarted = nowMS;
            } else if ((nowMS - shutdownStarted) >= (long long)shutdownSec * 1000) {
                dumpstack_gdb();
                WatchdogExit("shutdown did not complete", nowMS - shutdownStarted);
            }
            continue;
        }
        long long hb = s_mainLoopHeartbeat.load();
        if (hb == 0) {
            continue;
        }
        long long stalledMS = MonotonicMS() - hb;
        if (stalledMS < (long long)warnSec * 1000) {
            if (warned) {
                LogWarn(VB_GENERAL, "Main loop watchdog: loop resumed (was in '%s')\n",
                        GetMainLoopPhase());
                WarningHolder::RemoveWarning(59, "fppd main loop is stalled - the status shown may be stale and sync packets are not being processed");
                warned = false;
            }
            continue;
        }

        if (!warned) {
            warned = true;
            LogErr(VB_GENERAL, "Main loop watchdog: no main loop iteration for %lld seconds, stalled in '%s' — dumping thread state\n",
                   stalledMS / 1000, GetMainLoopPhase());
            WarningHolder::AddWarning(59, "fppd main loop is stalled - the status shown may be stale and sync packets are not being processed");
            WarningHolder::WriteWarningsFile();
            // Cheap and always available, so take it first: it names the
            // syscall and lock address of every thread even when the unwinder
            // cannot walk the stalled stack.
            DumpThreadStates();
            // The one diagnostic that says *where* it is stuck.  gdb stops the
            // process briefly; it is already doing nothing.
            dumpstack_gdb();
        }

        if (restartSec > 0 && stalledMS >= (long long)restartSec * 1000) {
            WatchdogExit("main loop stalled", stalledMS);
        }
    }
}

static void StartMainLoopWatchdog() {
    // 0 disables the watchdog entirely; a stall shorter than the warn time is
    // normal (a large sequence load, a slow media start).
    int warnSec = 0, restartSec = 0, shutdownSec = 0;
    ReadWatchdogTimeouts(warnSec, restartSec, shutdownSec);
    if (warnSec <= 0) {
        LogInfo(VB_GENERAL, "Main loop watchdog disabled (MainLoopStallTimeout=%d)\n", warnSec);
        return;
    }
    // Logged so a soak log answers "which timeouts was it actually using?"
    // without having to guess at what the settings file said at the time.
    LogInfo(VB_GENERAL, "Main loop watchdog: warn after %ds, restart after %ds%s, shutdown limit %ds\n",
            warnSec, restartSec, restartSec > 0 ? "" : " (restart disabled)", shutdownSec);
    s_mainLoopHeartbeat.store(MonotonicMS());
    s_mainLoopWatchdogRunning = true;
    // Detached on purpose: it outlives the main loop to supervise the shutdown
    // that follows it, and every exit path from there is _exit()/execlp(),
    // which takes the thread with it.  (A joinable file-static std::thread
    // reaching static destruction is its own crash -- see ShutdownFPPD.)
    std::thread(MainLoopWatchdog, warnSec, restartSec, shutdownSec).detach();
}

void MainLoop(void) {
    RegisterShutdownHandler(ShutdownFPPDCallback);

    PlaylistStatus prevFPPstatus = FPP_STATUS_IDLE;
    int sleepms = 50;
    int publishCounter = 200; // about 40 seconds after boot
    std::string publishReason("Startup");
    std::map<int, std::function<bool(int)>> callbacks;

    LogDebug(VB_GENERAL, "MainLoop()\n");

    int sock = Command_Initialize();
    LogDebug(VB_GENERAL, "Command socket: %d\n", sock);
    if (sock >= 0) {
        callbacks[sock] = [](int i) {
            MAIN_LOOP_PHASE("fpp command socket");
            CommandProc();
            return false;
        };
    }

    sock = multiSync->GetControlSocket();
    LogDebug(VB_GENERAL, "Multisync socket: %d\n", sock);
    if (sock >= 0) {
        callbacks[sock] = [](int i) {
            MAIN_LOOP_PHASE("multisync ProcessControlPacket");
            multiSync->ProcessControlPacket();
            return false;
        };
    }
    Bridge_Initialize(callbacks);

    APIServer apiServer;
    apiServer.Init();

    OutputMonitor::INSTANCE.Initialize(callbacks);
    GPIOManager::INSTANCE.Initialize(callbacks);
    PluginManager::INSTANCE.addControlCallbacks(callbacks);
    NetworkMonitor::INSTANCE.Init(callbacks);
    Sensors::INSTANCE.Init(callbacks);
    Variables::INSTANCE.Init();
    RecurringTasks::INSTANCE.Init();
    FileMonitor::INSTANCE.Initialize(callbacks);
    MDNSManager::INSTANCE.Initialize(callbacks);
    
    // Get the last release date from rpi-imager file to use as minimum valid date
    // Systems without RTC boot with filesystem timestamps, which will be older than the release
    // If clock shows a date before the last OS release, it's definitely wrong
    std::tm minValidDate = {};
    minValidDate.tm_year = 125;  // 2025 fallback
    minValidDate.tm_mon = 0;
    minValidDate.tm_mday = 1;
    Json::Value imagerRoot;
    if (LoadJsonFromFile(getFPPDDir("/rpi-imager/rpi-imager_falcon_player.json"), imagerRoot, JsonRoot::Object)) {
        if (imagerRoot.isMember("os_list") && imagerRoot["os_list"].isArray()) {
            std::time_t latestRelease = 0;
            // Find the latest release date across all OS images
            for (const auto& osEntry : imagerRoot["os_list"]) {
                if (osEntry.isMember("release_date")) {
                    std::string releaseDate = osEntry["release_date"].asString();
                    if (releaseDate.length() >= 10) {
                        // Parse "YYYY-MM-DD" format
                        std::tm releaseTime = {};
                        releaseTime.tm_year = std::stoi(releaseDate.substr(0, 4)) - 1900;
                        releaseTime.tm_mon = std::stoi(releaseDate.substr(5, 2)) - 1;
                        releaseTime.tm_mday = std::stoi(releaseDate.substr(8, 2));
                        std::time_t releaseTimestamp = std::mktime(&releaseTime);
                        if (releaseTimestamp > latestRelease) {
                            latestRelease = releaseTimestamp;
                            minValidDate = releaseTime;
                        }
                    }
                }
            }
        }
    }
    std::time_t minValidTime = std::mktime(&minValidDate);
    bool clockWarningAdded = false;

    StartChannelOutputThread();
    if (!getSettingInt("restarted")) {
        sequence->SendBlankingData();
    }
    bool alwaysTransmit = (bool)getSettingInt("alwaysTransmit");

    // A process killed by the main-loop watchdog leaves its show behind in
    // tmpfs instead of on the command line (there is no orderly re-exec to put
    // it there) -- fold it into the same resume settings a restart would have
    // set, before either resume path below reads them (issue #2727).
    ApplyStallResumeState();

    if (getFPPmode() & PLAYER_MODE) {
        // Don't start scheduler if clock is obviously wrong (date before last release)
        // This prevents scheduling issues on systems without RTC that boot with incorrect time
        // The scheduler will start when time is corrected via time jump detection
        std::time_t now = time(nullptr);
        
        if (now >= minValidTime) {
            scheduler->CheckIfShouldBePlayingNow();
        } else {
            struct tm timeinfo;
            localtime_r(&now, &timeinfo);
            LogWarn(VB_SCHEDULE, "Clock appears incorrect (date %04d-%02d-%02d before release), delaying scheduler start until time sync\n",
                    timeinfo.tm_year + 1900, timeinfo.tm_mon + 1, timeinfo.tm_mday);
            WarningHolder::AddWarning(55, "System clock not set - scheduler start delayed until time sync");
            clockWarningAdded = true;
        }

        // If a scheduled item covered the resume, CheckIfShouldBePlayingNow()
        // above already started it and cleared resumePlaylist.  Anything left
        // here is a show that was running with no schedule behind it when we
        // restarted ourselves to recover the video decoder -- start it, or the
        // player comes back idle and every synced remote sits on its last frame
        // waiting for sync packets that never arrive (issue #2727).
        std::string resumePlaylist = getSetting("resumePlaylist");
        if (getSettingInt("resumeUnscheduled") && !resumePlaylist.empty() &&
            Player::INSTANCE.GetStatus() == FPP_STATUS_IDLE) {
            int resumePosition = getSettingInt("resumePosition");
            int resumeRepeat = getSettingInt("resumeRepeat");
            LogInfo(VB_PLAYLIST, "Resuming unscheduled playlist '%s' at position %d (repeat %d) after restart\n",
                    resumePlaylist.c_str(), resumePosition, resumeRepeat);
            SetSetting("resumePlaylist", "");
            SetSetting("resumePosition", 0);
            SetSetting("resumeUnscheduled", 0);
            Player::INSTANCE.StartPlaylist(resumePlaylist, resumeRepeat, resumePosition);
        }
    }
    if (CommandManager::INSTANCE.HasPreset("FPPD_STARTED")) {
        CommandManager::INSTANCE.TriggerPreset("FPPD_STARTED");
    }

    for (auto& a : callbacks) {
        EPollManager::INSTANCE.addFileDescriptor(a.first, a.second);
    }

    multiSync->Discover();
    Events::Ready();

    // Wire up EPollManager timer to fire Timers, so epoll_wait/kevent
    // wakes precisely when the next timer is due
    EPollManager::INSTANCE.setTimerCallback([]() {
        Timers::INSTANCE.fireTimers();
    });

    LogInfo(VB_GENERAL, "Starting main processing loop\n");

    int lowestLogLevel = FPPLogger::INSTANCE.MinimumLogLevel();
    if (lowestLogLevel == LOG_EXCESSIVE)
        WarningHolder::AddWarning(2, EXCESSIVE_LOG_LEVEL_WARNING);
    else if (lowestLogLevel == LOG_DEBUG)
        WarningHolder::AddWarning(3, DEBUG_LOG_LEVEL_WARNING);

    int idleCount = 0;

    StartMainLoopWatchdog();

    while (runMainFPPDLoop) {
        s_mainLoopHeartbeat.store(MonotonicMS());
        MAIN_LOOP_PHASE("epoll/callbacks");
        EPollManager::WaitResult epollresult = EPollManager::INSTANCE.waitForEvents(sleepms);
        bool pushBridgeData = epollresult == EPollManager::WaitResult::SOME_TRUE;
        if (epollresult == EPollManager::WaitResult::INTERRUPTED) {
            // We get interrupted when media players finish
            continue;
        }
        if (epollresult == EPollManager::WaitResult::FAILED) {
            LogErr(VB_GENERAL, "Main epoll() failed: %s\n", FPPstrerror(errno));
            runMainFPPDLoop = 0;
            continue;
        }
        // Check to see if we need to start up the output thread.
        MAIN_LOOP_PHASE("channel output thread check");
        if ((!ChannelOutputThreadIsRunning()) &&
            ((PixelOverlayManager::INSTANCE.hasActiveOverlays()) ||
             (ChannelTester::INSTANCE.Testing()) ||
             (alwaysTransmit) || sequence->hasBridgeData() ||
             pushBridgeData)) {
            StartChannelOutputThread();
        }

        if (getFPPmode() & PLAYER_MODE) {
            // Keep the watchdog's idea of what is playing current -- it cannot
            // read this out of Player itself once the loop is stalled.
            RecordMainLoopShowSnapshot();

            if (Player::INSTANCE.IsPlaying()) {
                if (prevFPPstatus == FPP_STATUS_IDLE) {
                    sleepms = 10;
                }

                // Check again here in case PlayListPlayingInit
                // didn't find anything and put us back to IDLE
                if (Player::INSTANCE.IsPlaying()) {
                    MAIN_LOOP_PHASE("Player::Process");
                    Player::INSTANCE.Process();
                }
            }

            int reactivated = 0;
            if (Player::INSTANCE.GetStatus() == FPP_STATUS_IDLE) {
                if ((prevFPPstatus == FPP_STATUS_PLAYLIST_PLAYING) ||
                    (prevFPPstatus == FPP_STATUS_PLAYLIST_PAUSED) ||
                    (prevFPPstatus == FPP_STATUS_STOPPING_GRACEFULLY) ||
                    (prevFPPstatus == FPP_STATUS_STOPPING_GRACEFULLY_AFTER_LOOP)) {
                    MAIN_LOOP_PHASE("Player::Cleanup");
                    Player::INSTANCE.Cleanup();

                    if (Player::INSTANCE.GetForceStopped())
                        scheduler->CheckIfShouldBePlayingNow(0, Player::INSTANCE.GetScheduleEntry());
                    else
                        scheduler->CheckIfShouldBePlayingNow();

                    if (Player::INSTANCE.GetStatus() != FPP_STATUS_IDLE)
                        reactivated = 1;
                    else
                        sleepms = 50;
                }
            }

            if (reactivated)
                prevFPPstatus = FPP_STATUS_IDLE;
            else
                prevFPPstatus = Player::INSTANCE.GetStatus();

        } else if (getFPPmode() == REMOTE_MODE) {
            if (mediaOutputStatus.status == MEDIAOUTPUTSTATUS_PLAYING) {
                MAIN_LOOP_PHASE("Player::ProcessMedia");
                Player::INSTANCE.ProcessMedia();
            } else {
                MAIN_LOOP_PHASE("CheckSyncedMediaIdleTimeout");
                // Media that ran to its end and was never stopped by the
                // player (issue #2727) -- only checked when not playing, so
                // free-running through a sync gap is untouched.
                multiSync->CheckSyncedMediaIdleTimeout();
            }
        }
        
        // Only run scheduler if clock appears valid (same check as initial scheduler start)
        std::time_t now = time(nullptr);
        if (now >= minValidTime) {
            if (clockWarningAdded) {
                // clock was corrected (time sync) since startup — clear the warning
                WarningHolder::RemoveWarning(55, "System clock not set - scheduler start delayed until time sync");
                clockWarningAdded = false;
            }
            MAIN_LOOP_PHASE("scheduler");
            scheduler->ScheduleProc();
        }

        if (pushBridgeData) {
            MAIN_LOOP_PHASE("ForceChannelOutputNow");
            ForceChannelOutputNow();
        }
        bool doPing = false;
        if (epollresult == EPollManager::WaitResult::TIMEOUT) {
            idleCount++;
            if (idleCount >= 20) {
                doPing = true;
            }
        } else if (idleCount > 0) {
            doPing = true;
        } else {
            idleCount--;
            if (idleCount < -20) {
                doPing = true;
            }
        }
        if (doPing) {
            idleCount = 0;
            MAIN_LOOP_PHASE("multisync PeriodicPing");
            multiSync->PeriodicPing();
            if (--publishCounter < 0) {
                PublishStatsBackground(publishReason);
                // counting down is less CPU then the time check every cycle
                publishCounter = 60480;
                publishReason = "normal";
            }
            // also do the periodic work in the api server while idle
            MAIN_LOOP_PHASE("apiServer periodicWork");
            apiServer.periodicWork();
        }
        MAIN_LOOP_PHASE("timers");
        Timers::INSTANCE.fireTimers();
        MAIN_LOOP_PHASE("curls");
        CurlManager::INSTANCE.processCurls();
        MAIN_LOOP_PHASE("recurring tasks");
        RecurringTasks::INSTANCE.tick();
        IfCommand::tick();
        MAIN_LOOP_PHASE("GPIO inputs");
        GPIOManager::INSTANCE.CheckGPIOInputs();
    }
    MAIN_LOOP_PHASE("loop exited");
    FileMonitor::INSTANCE.Cleanup();

    LogInfo(VB_GENERAL, "Stopping channel output thread.\n");
    StopChannelOutputThread();

    Bridge_Shutdown();
    EPollManager::INSTANCE.shutdown();
    LogInfo(VB_GENERAL, "Main Loop complete, shutting down.\n");
}

void CreateDaemon(void) {
    /* Fork and terminate parent so we can run in the background */
    /* Fork off the parent process */
    pid = fork();
    if (pid < 0) {
        exit(EXIT_FAILURE);
    }
    /* If we got a good PID, then
        we can exit the parent process. */
    if (pid > 0) {
        exit(EXIT_SUCCESS);
    }

    /* Change the file mode mask */
    umask(0);

    /* Create a new SID for the child process */
    sid = setsid();
    if (sid < 0) {
        /* Log any failures here */
        exit(EXIT_FAILURE);
    }

    /* Fork a second time to get rid of session leader */
    /* Fork off the parent process */
    pid = fork();
    if (pid < 0) {
        exit(EXIT_FAILURE);
    }
    /* If we got a good PID, then
      we can exit the parent process. */
    if (pid > 0) {
        exit(EXIT_SUCCESS);
    }

    /* Close out the standard file descriptors */
    close(STDIN_FILENO);
    close(STDOUT_FILENO);
    close(STDERR_FILENO);
}

void PublishStatsForce(std::string reason) {
    SetThreadName("FPP-PubStats");
    std::string result("");
    urlPost("http://localhost/api/statistics/usage?reason=" + reason, "", result);
    LogInfo(VB_GENERAL, "Publishing statistics because of \"%s\" = %s\n", reason.c_str(), result.c_str());
}

void PublishStatsBackground(std::string reason) {
    // No need to publish more than once every 10 days if fppd is up that long
    static auto lastPublish = std::chrono::system_clock::now() - std::chrono::hours(10 * 24);
    auto now_ts = std::chrono::system_clock::now();
    auto hours = std::chrono::duration_cast<std::chrono::hours>(now_ts - lastPublish);

    // Check 10 days
    if (hours.count() >= (10 * 24)) {
        lastPublish = now_ts;
        if (getSetting("statsPublish") == "Enabled") {
            std::thread t(PublishStatsForce, reason);
            t.detach();
        } else {
            LogInfo(VB_GENERAL, "Not Publishing statistics as mode is '%s'\n", getSetting("statsPublish").c_str());
        }
    } else {
        LogDebug(VB_GENERAL, "PublishStats called, but not been 10 days yet.\n");
    }
}
