#! /usr/bin/php
<?php

// detect and initialize the eeprom, only support 24c256 chips for now
if (!file_exists("/sys/bus/i2c/devices/2-0050/eeprom")) {
    file_put_contents("/sys/bus/i2c/devices/i2c-2/new_device", "24c256 0x50");
}

$fp = fopen('/sys/bus/i2c/devices/2-0050/eeprom', 'wb');
$header = pack("a6", "FPP02");
fwrite($fp, $header);

$cape = pack("a26", $argv[1]);
fwrite($fp, $cape);
$capev = pack("a10", $argv[2]);
fwrite($fp, $capev);
$serial = pack("a16", $argv[3]);
fwrite($fp, $serial);
$eedir = $argv[4];

$zip_file = tempnam("/tmp", $argv[1] . "-eeprom");
unlink($zip_file);
$zip_file = $zip_file . ".zip";
exec("cd $eedir ; zip -9r $zip_file * -x cape-info.json -x **/._* 2>&1", $output, $result);
if ($result != 0) {
    var_dump($output);
}

$jsonlen = filesize($eedir . "/cape-info.json");
$jsonLenStr = sprintf("%d", $jsonlen);
fwrite($fp, pack("a6", $jsonLenStr));
fwrite($fp, pack("a2", "0"));
fwrite($fp, pack("a64", "tmp/cape-info.json"));
$json = file_get_contents($eedir . "/cape-info.json");
fwrite($fp, $json);

$zipLen = filesize($zip_file);
$zipLenStr = sprintf("%d", $zipLen);
fwrite($fp, pack("a6", $zipLenStr));
fwrite($fp, pack("a2", "1"));
fwrite($fp, pack("a64", "tmp/cape-info.zip"));
$zipData = file_get_contents($zip_file);
fwrite($fp, $zipData);

fwrite($fp, pack("a6", "0"));
fclose($fp);

unlink($zip_file);
file_put_contents("/sys/bus/i2c/devices/i2c-2/delete_device", "0x50");

?>

