<?

/**
 * Reads and returns the parsed settings.json metadata file.
 *
 * @return array Associative array of settings metadata.
 */
function ReadSettingsJSON()
{
    global $settings;
    $json = file_get_contents($settings['fppDir'] . '/www/settings.json');

    return json_decode($json, true);
}

/**
 * Get value of setting
 *
 * Get info about a particular setting, including its current `value`.
 *
 * @route GET /api/settings/{SettingName}
 * @response 200 Setting metadata and current value
 * ```json
 * {
 *   "name": "AudioFormat",
 *   "description": "Audio Output Format",
 *   "tip": "The Audio Format generated by the decoder",
 *   "level": 1,
 *   "restart": 2,
 *   "default": 0,
 *   "type": "select",
 *   "options": {
 *     "Default": 0,
 *     "MP3": 1,
 *     "Ogg": 2,
 *     "Flac": 3
 *   }
 * }
 * ```
 */
function GetSetting()
{
    global $settings;

    $sInfos = ReadSettingsJSON();
    $settingName = params('SettingName');

    if (isset($sInfos['settings'][$settingName])) {
        $sInfo = $sInfos['settings'][$settingName];
    } else {
        $sInfo = array();
    }

    if (isset($settings[$settingName])) {
        $sInfo['value'] = $settings[$settingName];
    }

    if (isset($sInfo['optionsURL'])) {
        $json = "";
        if (preg_match('/^\//', $sInfo['optionsURL'])) {
            $json = file_get_contents($sInfo['optionsURL']);
        } else {
            $json = file_get_contents("http://" . $_SERVER['SERVER_ADDR'] . "/" . $sInfo['optionsURL']);
        }

        $sInfo['options'] = json_decode($json, true);
    }

    return json($sInfo);
}

/**
 * Set value for setting
 *
 * Sets the value for a specific setting.
 *
 * @route PUT /api/settings/{SettingName}
 * @body "0"
 * @response 200 Setting saved
 * ```json
 * {"status": "OK"}
 * ```
 */
function PutSetting()
{
    global $SUDO, $settings;
    $value = file_get_contents('php://input');
    $setting = params('SettingName');

    if ($setting == 'GPIOFanTemperature' && isset($settings['temperatureInF']) && $settings['temperatureInF'] == 1) {
        $value = round(($value - 32) * 5 / 9);
    }

    WriteSettingToFile($setting, $value);

    // Callers can pass ?skipApply=1 to persist the value WITHOUT running the
    // (sometimes expensive) side effects that apply it. This is used to write a
    // value that a different setting's apply step will pick up - e.g. the initial
    // setup page writes osPassword with skipApply so that only the single
    // osPasswordEnable apply runs chpasswd (yescrypt, ~3s) rather than running it
    // twice (once for the value, once for the enable).
    $skipApply = isset($_GET['skipApply']) && $_GET['skipApply'] == '1';

    if ($skipApply) {
        // Value already written above; the caller will apply it via another setting.
    } else if (str_starts_with($setting, "LogLevel")) {
        SendCommand("LogLevel,$setting,$value,");
    } else if ($setting == "HostName") {
        $value = preg_replace("/[^-a-zA-Z0-9]/", "", $value);
        // Run all the hostname updates in a single sudo/bash invocation rather than
        // four separate sudo calls (each fork+sudo is slow on a BBB). This also
        // fixes a latent bug: the original had no ';' before "hostname $value", so
        // sed swallowed "sudo hostname $value" as extra filenames and the running
        // hostname was never actually updated. $value is sanitized to [-a-zA-Z0-9].
        exec(
            $SUDO . " bash -c " . escapeshellarg(
                "sed -i 's/^.*\$/$value/' /etc/hostname ; " .
                "sed -i '/^127.0.1.1[^0-9]/d' /etc/hosts ; " .
                "sed -i '\$a127.0.1.1 $value' /etc/hosts ; " .
                "hostname $value"
            ),
            $output,
            $return_val
        );
    } else if ($setting == "EnableRouting") {
        if ($value != "1") {
            $value = "0";
        }
        exec(
            $SUDO . " sed -i '/net.ipv4.ip_forward/d' /etc/sysctl.conf; " .
            $SUDO . " sed -i '\$anet.ipv4.ip_forward = $value' /etc/sysctl.conf ; " .
            $SUDO . " sysctl --system",
            $output,
            $return_val
        );
    } else if ($setting == "storageDevice") {
        if ($settings['BeaglePlatform']) {
            exec('findmnt -n -o SOURCE / | colrm 1 5', $output, $return_val);
            $rootDevice = $output[0];
            unset($output);
        } else {
            exec('lsblk -l | grep " /$" | cut -f1 -d" "', $output, $return_val);
            $rootDevice = $output[0];
            unset($output);
        }
        if ($value == "--none--") {
            $value = $rootDevice;
        } else {
            $fsckOrder = "0";
            exec($SUDO . " file -sL /dev/$value | grep FAT", $output, $return_val);
            if ($output[0] == "") {
                unset($output);
                exec($SUDO . " file -sL /dev/$value | grep BTRFS", $output, $return_val);

                if ($output[0] == "") {
                    unset($output);
                    exec($SUDO . " file -sL /dev/$value | grep DOS", $output, $return_val);
                    if ($output[0] == "") {
                        # probably ext4
                        $options = "defaults,noatime,nodiratime,nofail";
                        $fsckOrder = "2";
                    } else {
                        # exFAT probably
                        $options = "defaults,noatime,nodiratime,exec,nofail,uid=500,gid=500";
                        $fsckOrder = "2";
                    }
                } else {
                    # BTRFS, turn on compression since fseq files are very compressible
                    $options = "defaults,noatime,nodiratime,compress=zstd,nofail";
                    $fsckOrder = "0";
                }
            } else {
                # FAT filesystem
                $options = "defaults,noatime,nodiratime,exec,nofail,flush,uid=500,gid=500";
                $fsckOrder = "2";
            }
        }
        if (preg_match("/$rootDevice/", $value)) {
            exec($SUDO . " sed -i 's/.*home\/fpp\/media/#\/dev\/sda1    \/home\/fpp\/media/' /etc/fstab", $output, $return_val);
        } else {
            exec($SUDO . " sed -i 's/.*home\/fpp\/media.*/\/dev\/$value	\/home\/fpp\/media	auto	$options	0	$fsckOrder /' /etc/fstab", $output, $return_val);
        }
        unset($output);
    } else if ($setting == "AudioOutput") {
        SetAudioOutput($value);
        // In Simple PipeWire mode, the AudioOutput selection drives the
        // synthesised PipeWire audio group config — re-apply it now.
        $settings[$setting] = $value;
        if (IsSimplePipeWireBackend($settings)) {
            ob_start();
            ApplyPipeWireSimpleConfig();
            ob_end_clean();
        }
    } else if ($setting == "VideoOutput") {
        ApplySetting($setting, $value);
        SendCommand("SetSetting,$setting,$value,");
        // In Simple PipeWire mode, the VideoOutput selection drives the
        // synthesised PipeWire video group config — re-apply it now.
        $settings[$setting] = $value;
        if (IsSimplePipeWireBackend($settings)) {
            ob_start();
            ApplyPipeWireSimpleConfig();
            ob_end_clean();
        }
    } else if ($setting == "MediaBackend") {
        ApplySetting($setting, $value);
        SendCommand("SetSetting,$setting,$value,");
        // When switching INTO Simple PipeWire mode, generate and apply the
        // single-card / single-display config from the existing AudioOutput
        // / VideoOutput selections.  Advanced-mode JSON files are left
        // untouched so users can switch back without losing custom configs.
        $settings[$setting] = $value;
        if (IsSimplePipeWireBackend($settings)) {
            ob_start();
            ApplyPipeWireSimpleConfig(true);
            ob_end_clean();
        } else if (IsPipeWireBackend($settings)) {
            // Switching INTO Advanced PipeWire mode: re-apply the saved
            // advanced audio/input-group config so the regenerated graph
            // and PipeWireSinkName match.  Without this, PipeWireSinkName
            // is left at whatever the previous mode set (e.g. the Simple
            // mode "fpp_group_default"), which does not exist in the
            // advanced graph — fppd's stream is then orphaned and silent.
            // Audio groups first (output sinks), then input groups (mix
            // buses target the output groups and write the final
            // PipeWireSinkName, e.g. fpp_input_mix_bus_1).
            ob_start();
            ApplyPipeWireAudioGroups(null, true);
            ApplyPipeWireInputGroups(true);
            ob_end_clean();
        }
        // Config files are written above (fast). Now background fppinit setupAudio +
        // PipeWire service restarts so the HTTP response returns immediately.
        // Using < /dev/null ensures the background process fully detaches from Apache.
        $fppDir = $settings['fppDir'];
        $bgScript =
            $SUDO . " " . escapeshellarg($fppDir . "/src/fppinit") . " setupAudio\n" .
            $SUDO . " /usr/bin/systemctl restart fpp-pipewire.service\n" .
            "sleep 0.5\n" .
            $SUDO . " /usr/bin/systemctl restart fpp-wireplumber.service\n" .
            "for i in 1 2 3 4 5 6 7 8 9 10; do [ -e /run/pipewire-fpp/pipewire-0 ] && break; sleep 0.25; done\n" .
            $SUDO . " /usr/bin/systemctl restart fpp-pipewire-pulse.service\n";
        exec("nohup bash -c " . escapeshellarg($bgScript) . " < /dev/null > /dev/null 2>&1 &");
    } else if ($setting == "EnableTethering") {
        $ssid = ReadSettingFromFile("TetherSSID");
        $psk = ReadSettingFromFile("TetherPSK");
        if ($ssid == "") {
            $ssid = "FPP";
            WriteSettingToFile("TetherSSID", $ssid);
        }
        if ($psk == "") {
            $psk = "Christmas";
            WriteSettingToFile("TetherPSK", $psk);
        }
    } else if ($setting == "BBBLeds0" || $setting == "BBBLeds1" || $setting == "BBBLeds2" || $setting == "BBBLeds3" || $setting == "BBBLedPWR") {
        exec($SUDO . " " . $settings['fppDir'] . "/src/fppinit configureBBB", $output);
    } else if ($setting == "scheduling") {
        SendCommand("EnableScheduling,$value,");
    } else {
        ApplySetting($setting, $value);
        SendCommand("SetSetting,$setting,$value,");
    }

    //Callers saving many settings in a row (e.g. the initial setup page) can pass
    //?skipBackup=1 to avoid generating a full configuration backup on every single
    //setting - the backup is expensive on slower devices - and instead create one
    //backup once all the settings have been saved.
    $skipBackup = isset($_GET['skipBackup']) && $_GET['skipBackup'] == '1';

    //If the setting being set isn't the reboot or restart flag (we don't want to trigger a backup on these)
    if (!$skipBackup && in_array(ltrim(rtrim($setting)), array('restartFlag', 'rebootFlag', 'currentHeaderSensor')) === false) {
        //Make a call to the configuration backup API endpoint so we can generate a backup
        $backup_comment = GenerateBackupComment($setting, $value);
        GenerateBackupViaAPI($backup_comment);
    }

    $status = array("status" => "OK");
    return json($status);
}

/**
 * Get all settings.json
 *
 * Returns the `settings.json` metadata file as a JSON list of settings.
 *
 * @route GET /api/settings
 * @response 200 All settings metadata
 * ```json
 * {
 *   "settingGroups": {
 *     "BBBLeds": {
 *       "description": "BeagleBone LEDs",
 *       "platforms": ["BeagleBone Black"],
 *       "settings": ["BBBLeds0", "BBBLeds1", "BBBLeds2", "BBBLeds3", "BBBLedPWR"]
 *     }
 *   },
 *   "settings": {
 *     "alwaysTransmit": {}
 *   }
 * }
 * ```
 */
function GetSettings()
{
    global $settings;
    return file_get_contents($settings['fppDir'] . '/www/settings.json');
}

/**
 * Get current time
 *
 * Returns the current system time as a formatted string.
 *
 * @route GET /api/time
 * @response 200 Current system time
 * ```json
 * {"time": "Tue Apr 02 08:06:34 EDT 2019"}
 * ```
 */
function GetTime()
{
    $result = array();
    //$result['time'] = date('D M d H:i:s T Y'); // Apache needs restarting after a timezone change
    $result['time'] = exec('date');
    return json($result);
}

/**
 * Set sub-value
 *
 * Updates a sub-value held as JSON within a setting's value. Only valid for settings stored as JSON.
 *
 * @route PUT /api/settings/{SettingName}/jsonValueUpdate
 * @body "raw json of hierarchy to update"
 * @response 200 Sub-value updated
 * ```json
 * {"status": "OK"}
 * ```
 */
function UpdateJSONValueSetting()
{
    global $SUDO;
    $new_json_sub_value = file_get_contents('php://input');
    $new_json_sub_value = trim($new_json_sub_value, " \t\n\r\0\x0B\"");
    $new_json_sub_value = str_replace("\\", "", $new_json_sub_value);
    $settingName = params('SettingName');

    $orig_json_value = ReadSettingFromFile($settingName);

    if (json_object_validate($orig_json_value) && json_object_validate($new_json_sub_value)) {

        $OriginArrayData = json_decode($orig_json_value, true);

        $replacementDataArray = json_decode($new_json_sub_value, true);

        $newArrayData = array_replace_recursive($OriginArrayData, $replacementDataArray);
        $new_json_value = json_encode($newArrayData);

        WriteSettingToFile($settingName, $new_json_value);

        $status = array("status" => "OK");
    } else {
        $status = array("status" => "Error updating JSON value");
    }
    return json($status);
}
