    <table width="900" border="0" cellspacing="5" cellpadding="5">
    <tr>
      <td width="36%"><a href="http://www.falconchristmas.com"><img src="images/falconlogo.png" width="250" height="141" /></a></td>
      <td width="28%" align="center" valign="middle"><h1><strong><em>Falcon Pi Player</em></strong></h1><h1><strong><em>FPP</em></strong></h1>
        </td>
      <td width="36%"><p align="center"><a href="http://raspberrypi.org"><img src="images/large_Raspberry_Pi_Logo_4.png" width="180" height="180" /></a></p></td>
    </tr>
   </table>

    <div id="fppMenu" class="ddsmoothmenu">
    <ul>
    <li><a href="index.php">Status/Control</a></li>
    <li><a href="uploadFile.php">File Manager</a></li>
    <li><a href="playLists.php">Playlists</a></li>
    <li><a href="Universes.php">Outputs</a>
			<ul>
		    <li><a href="Universes.php">Universes</a></li>
		    <li><a href="PixelnetDMX.php">Pixelnet/DMX</a></li>
			</ul>
		</li>
    <li><a href="scheduler.php">Scheduler</a></li>
    </ul>
    <br style="clear: left" />
    </div>

