    <table width="900" border="0" cellspacing="5" cellpadding="5">
    <tr>
      <td width="36%"><a href="http://www.falconchristmas.com"><img src="images/falconlogo.png" width="240" height="130" /></a></td>
      <td width="28%" align="center" valign="middle"><h1><strong><em>Falcon Pi Player</em></strong></h1><h1><strong><em>FPP</em></strong></h1>
        </td>
      <td width="36%"><p align="center"><a href="http://raspberrypi.org"><img src="images/large_Raspberry_Pi_Logo_4.png" width="130" height="130" /></a></p></td>
    </tr>
   </table>

    <div id="fppMenu" class="ddsmoothmenu">
    <ul>
      <li><a href="#">Basic Setup</a>
        <ul>
          <li><a href="uipassword.php">Set UI Password</a></li>
          <li><a href="timeconfig.php">Config/Set Time</a></li>
          <li><a href="networkconfig.php">Network</a></li>
          <li><a href="playerkconfig.php">Player Mode</a></li>
        </ul>
      </li>
      <li><a href="#">Content Setup</a>
        <ul>
          <li><a href="uploadfile.php">Source Files</a></li>
          <li><a href="playlists.php">Playlists</a></li>
          <li><a href="scheduler.php">Scheduler</a></li>
          <li><a href="video.php">Videos</a></li>
        </ul>
      </li>
      <li><a href="#">Output Setup</a>
        <ul>
          <li><a href="universes.php">Universe</a></li>
          <li><a href="pixelnetdmx.php">Pixelnet/DMX</a></li>
          <li><a href="rds.php">Radio RDS</a></li>
        </ul>
      </li>
      <li><a href="index.php">Status/Control</a></li>
      <li><a href="http://falconchristmas.com/wiki/index.php5/FPP">Wiki/Help</a></li>
    </ul>
    <br style="clear: left" />
    </div>